### PR TITLE
TaxData Changes to Create UBI Ready PUF

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR makes a number of changes in order to produce a new PUF that contains additional variables needed for implementing a universal basic income function into Tax-Calculator. 

1. Updates the SAS code so that the new matched PUF contains the necessary variables.
2. Updates the PUF stage 2 notebook to fit the new repo structure
3. Updates `stage2.py` in the `puf_stage2` directory to create a new weights file associated with the new PUF.

A new weights file had to be created for the PUF because we are still encountering the issue discussed in PR #39. When I run the SAS files used to create the matched PUF on my machine the final file has eight fewer records than the PUF currently used in Tax-Calc. At the time this was first brought up for discussion, nobody was able to pin down the cause beyond a reasonable doubt and we still have not reached a conclusion, but one theory is that it boils down to a step in the matching process that uses a random number generator and because John and I have different versions of SAS our random number generators also differ. @MattHJensen, @Amy-Xu, and I have decided that at this point it would be best if we just made the switch to the files I can produce because it is holding up other work.

This issue may also become obsolete when the translation of the SAS code to Python is complete and we make that transition as well.

I will be opening up a corresponding Tax-Calc PR shortly.

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey,

Can you explain which new variables are being added to the `puf.csv` file and why they are being added?

So, am I correct in my understanding, that the new `puf_weights.csv` file has nothing to do with the new variables that are being added to the `puf.csv` file?

@MattHJensen @Amy-Xu

**Comment by andersonfrailey** [comment]
@martinholmer asked:
> Can you explain which new variables are being added to the puf.csv file and why they are being added?

Of course. Slipped my mind to do so in the original post. 
* `nu18, n1821, n21` are all being added to work with the UBI function that will be implemented in Tax-Calc. They hold the number of people under 18, between 18 and 21, and over 21 in a tax unit. There are three variables rather than just one for the total number of people so that different UBI amounts can be set depending on the age of the person receiving the benefit.
* `ssi, ssip, ssis, snap, snapp, snaps, medicarex, medicarexp, medicarexs` hold imputed SSI, SNAP, and Medicare benefits for the tax unit, the primary taxpayer, and their spouse. Theses were imputed by @Amy-Xu and are to be used in a project she is working on with @MattHJensen and myself.
* `ssi_participation, snap_participation` were also created by @Amy-Xu for the previously mentioned project. They indicate whether participation in the SSI and SNAP programs was imputed or not.

>So, am I correct in my understanding, that the new puf_weights.csv file has nothing to do with the new variables that are being added to the puf.csv file?

Correct. The new `puf_weights.csv` file is only needed because the new PUF file has a different number of records.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> `nu18`, `n1821`, `n21` are all being added to work with the UBI function that will be implemented in Tax-Calc. They hold the number of people under 18, between 18 and 21, and over 21 in a tax unit. 

Is the sum of these three new variables equal to `XTOT` for each filing unit?

@andersonfrailey said:
> `ssi`, `ssip`, `ssis`, `snap`, `snapp`, `snaps`, `medicarex`, `medicarexp`, `medicarexs` hold imputed SSI, SNAP, and Medicare benefits for the tax unit, the primary taxpayer, and their spouse. Theses were imputed by @Amy-Xu and are to be used in a project she is working on with @MattHJensen and myself.

`ssi_participation`, `snap_participation` were also created by @Amy-Xu for the previously mentioned project. They indicate whether participation in the SSI and SNAP programs was imputed or not.

Why are these benefits being added to the Tax-Calculator input file?  I thought the Benefits project has its own GitHub repository.   These ELEVEN extra variables have nothing to do with UBI, right?

**Comment by Amy-Xu** [comment]
@martinholmer Martin, let me add one point here. Yes, we do have a separate repo for the Benefit project. All the imputations we have done in that repo is based raw CPS March Supplement data, at the level of each specific program -- individual or household. 

Eventually we want to use those data to analyze a UBI reform, in terms of how much we will have from removing welfare and transfer programs as well as tax preferences. However, everything will be in tax-unit when we analyze UBI reforms, which means keeping welfare data at individual or household level is not convenient for this purpose. Thus we would want to fold those imputed data into tax-unit to facilitate our UBI reforms. In addition, we want to do the labor supply effect at tax-unit level as well. So all MTRs needs to be at tax-unit level. Thus, all these extra variables have something to do with UBI. Does that make sense?

**Comment by martinholmer** [comment]
@Amy-Xu said:
> Let me add one point here. Yes, we do have a separate repo for the Benefit project. All the imputations we have done in that repo is based raw CPS March Supplement data, at the level of each specific program -- individual or household.
>
> Eventually we want to use those data to analyze a UBI reform, in terms of how much we will have from removing welfare and transfer programs as well as tax preferences. However, everything will be in tax-unit when we analyze UBI reforms, which means keeping welfare data at individual or household level is not convenient for this purpose. Thus we would want to fold those imputed data into tax-unit to facilitate our UBI reforms. In addition, we want to do the labor supply effect at tax-unit level as well. So all MTRs needs to be at tax-unit level. Thus, all these extra variables have something to do with UBI. Does that make sense?

Yes.  Thanks for the explanation.

**Comment by andersonfrailey** [comment]
@martinholmer asked:
> Is the sum of these three new variables equal to XTOT for each filing unit?

No. According to the documentation for the [2009 public use file](http://users.nber.org/~taxsim/gdb/gdb09.pdf), which is where the `XTOT` variable comes from, `XTOT` is capped at 5 per tax unit. However, when you look at the tax units created from the CPS file and matched with the PUF file, there are as many as 12 people associated with a tax unit. Those three additional variables make it possible to get a truly accurate population count for the UBI.

I believe @Amy-Xu effectively answered your second question, but is there any other information you want that I might be able to add?

**Comment by martinholmer** [comment]
@andersonfrailey said:
> No. According to the documentation for the 2009 public use file, which is where the XTOT variable comes from, XTOT is capped at 5 per tax unit. However, when you look at the tax units created from the CPS file and matched with the PUF file, there are as many as 12 people associated with a tax unit. Those three additional variables make it possible to get a truly accurate population count for the UBI.

Are you saying that if IRS has XTOT=3 for a filing unit and we statistically match to that filing unit a CPS tax-filing-unit record with 7 people in it, that the sum of the three new UBI variables will be 7?
If so, that sounds like a lot of noise in the data being used in the tax simulation.

> I believe @Amy-Xu effectively answered your second question, but is there any other information you want that I might be able to add?

Yes she did and you've fully explained the nature of the new variables.  Thanks.

**Comment by andersonfrailey** [comment]
@martinholmer 
> Are you saying that if IRS has XTOT=3 for a filing unit and we statistically match to that filing unit a CPS tax-filing-unit record with 7 people in it, that the sum of the three new UBI variables will be 7?
If so, that sounds like a lot of noise in the data being used in the tax simulation.

This is a good point. Right now there is no perfect way to control for this.

During the matching process, both the public use file and the CPS tax units are partitioned based on filing status (single, joint, dependent, etc.) so we won't have a problem with say a single-filer in the PUF being matched with a joint-filing CPS tax unit with 7 people in it. Additionally, the number of dependents on a tax unit is factored into the match so bigger units will tend to be matched with other large units. Again, it is not perfect because of the limitations on how many dependents are represented in the public use file, but it should at least reduce some of the noise.

I'm open to any ideas that could be worked in, but for now I can't think of a more effective way to handle it.

**Comment by martinholmer** [comment]
@andersonfrailey answered in taxdata PR #83:
>> Are you saying that if IRS has XTOT=3 for a filing unit and we statistically match to that filing unit a CPS tax-filing-unit record with 7 people in it, that the sum of the three new UBI variables will be 7?
>> If so, that sounds like a lot of noise in the data being used in the tax simulation.
>
> This is a good point. Right now there is no perfect way to control for this.
>
> During the matching process, both the public use file and the CPS tax units are partitioned based on filing status (single, joint, dependent, etc.) so we won't have a problem with say a single-filer in the PUF being matched with a joint-filing CPS tax unit with 7 people in it. Additionally, the number of dependents on a tax unit is factored into the match so bigger units will tend to be matched with other large units. Again, it is not perfect because of the limitations on how many dependents are represented in the public use file, but it should at least reduce some of the noise.
>
> I'm open to any ideas that could be worked in, but for now I can't think of a more effective way to handle it.

You are right that this is a thorny problem with the IRS PUF data.  There is probably no easy fix to these problems.  Certain right now is not a good time to stop other work to focus on this matter.

**Comment by martinholmer** [comment]
@Amy-Xu said in taxdata #83 about adding SSI and SNAP and Medicare data to `puf.csv`:
> Yes, we do have a separate repo for the Benefit project. All the imputations we have done in that repo is based raw CPS March Supplement data, at the level of each specific program -- individual or household.
>
> Eventually we want to use those data to analyze a UBI reform, in terms of how much we will have from removing welfare and transfer programs as well as tax preferences. However, everything will be in tax-unit when we analyze UBI reforms, which means keeping welfare data at individual or household level is not convenient for this purpose. Thus we would want to fold those imputed data into tax-unit to facilitate our UBI reforms. In addition, we want to do the labor supply effect at tax-unit level as well. So all MTRs needs to be at tax-unit level. Thus, all these extra variables have something to do with UBI. Does that make sense?

On further thought, yes your benefits project analysis plan makes sense, but your explanation doesn't provide any reason to add the eleven SSI-SNAP-Medicare variables to the `puf.csv` file used by TaxBrain.  In a recent conversation @MattHJensen stated a concern about the amount of data being uploaded to TaxBrain.  Adding these eleven SSI-SNAP-Medicare variables to the `puf.csv` doesn't seem to be necessary for your benefits project.  What your explanation says is that the benefits project needs an augmented data file to run through Tax-Calculator.  So, why don't you get that file from the enhancements in this PR.  And then once you have that file (let's call it the `pufben.csv` file), @andersonfrailey can add these eleven SSI-SNAP-Medicare variables to the `UNUSED_READ_VARS` list in the `taxdata/puf_data/finalprep.py` script?  That way, you can process your `pufben.csv` file with Tax-Calculator (since the extra eleven variables will simply be ignored) and Matt can be happy that the size of the `puf.csv` file used by TaxBrain has not unnecessarily increased in size.

**Comment by martinholmer** [comment]
@andersonfrailey,  Please split the current taxdata pull request #83 into two separate pull requests: one PR that adds the three new n* variables needed for UBI benefit calculation in Tax-Calculator and handles the redo of the weights; and another PR that deals with the eleven SSI-SNAP-Medicare variables.  There are too many unrelated things combined in #83.

**Comment by martinholmer** [comment]
@andersonfrailey, Thanks for sending me your copies of the `cps-matched-puf.csv` file based on your #83 work and the file that is produced by the `cd puf_data; python finalprep.py`  command.  I've called this second file you sent `AF-benpuf.csv`.

Maybe I'm doing something wrong but I cannot replicate your work.  Here is what I did to see if I could produce the same `finalprep.py` output as you sent in the `AF-benpuf.csv` file.
```
taxdata$ ./gitpr 83
taxdata$ cd puf_data
puf_data$ python finalprep.py 
puf_data$ ls -l *puf.csv
-rw-r--r--@ 1 mrh  staff   75274205 Mar 21 13:34 AF-benpuf.csv
-rw-r--r--@ 1 mrh  staff  178345362 Mar 21 13:33 cps-matched-puf.csv
-rw-r--r--  1 mrh  staff  104713177 Mar 22 07:24 puf.csv
```
Notice the large size difference between the `puf.csv` and `AF-benpuf.csv` files.
I'm able to confirm that both those files contain 219806 records as follows:
```
puf_data$ awk -F, 'NR>1{n++}END{print n}' AF-benpuf.csv
219806
puf_data$ awk -F, 'NR>1{n++}END{print n}' puf.csv
219806
```
So it must be that the `puf.csv` file I generated has more variables than the `AF-benpuf.csv` file you sent.  Here is the list of variable names in the `puf.csv` file but not in the `AF-benpuf.csv` file:
```
> SOISEQ
> age_dep1
> age_dep2
> age_dep3
> age_dep4
> age_dep5
> age_oldest
> age_youngest
> cpsseq
> e07140
> e52852
> e52872
> finalseq
> h_seq
> head_age
> i
> jcps25
> jcps28
> jcps35
> jcps38
> medicarex_dep
> p86421
> peridnum
> prodseq
> snap_dep
> snap_participation
> sp_ptr
> spouse_age
> ssi_dep
> ssi_participation
> ssis
> wt
```
So, it looks like the PR #83 `puf_data/finalprep.py` code is not the code you used to generate the `AF-benpuf.csv` file you sent me.  Or maybe there is another explanation for why I can't replicate your work.  Did I do something wrong?  Any thoughts would be welcome.

**Comment by martinholmer** [comment]
@andersonfrailey,
After discussing the situation with @MattHJensen, I'm going to merge taxdata pull request #83 as it is.  Thanks for all the work on that.  And then, before we do anything else, I will revise the `puf_data/finalprep.py` script to have a switch that can be used to generate a `puf.csv` file that either (a) excludes all the new variables related to the Benefits Project or (b) includes all those new variables.  This means that if we ever need to generate a benfits-plus-puf CSV file for the Benefits Project, all that will be needed is to flip the switch.

Once that `finalprep.py` enhancement is completed we will be in a position to prepare a Tax-Calculator pull request that uses the new no-benefit-variables `puf.csv` file, which will be different from the `puf.csv` being used now because of the slightly different record count and weights.

In that conversation with @MattHJensen, he asked if the values for variables in the old `puf.csv` file were the same as the values in the new `puf.csv`.  It turns out that this question is more difficult to answer than you might think because of the records differences.   The old file had 219814 records while the new file has 219806 records, which is only eight less.  But the RECID values in the two files agree in only for 187123 records, probably because of random-number-stream differences.  As best as I can tell the IRS-SOI variables have the same values as before.  But the variables from the CPS are not the same record by record.  For example, the `age_head` and `age_spouse` values are different in almost all of the records with the same RECID value.  The value of `age_head` differs in 181480 of the 187123 records that can be compared, and the value of `age_spouse` differs in 171637 of the 187123 records that can be compared.  I'll post the script that generated these comparison results in another comment to #83, so that we have some evidence about the nature of the changes caused by pull request #83.

**Comment by martinholmer** [comment]
This comment on taxdata pull request #83 provides information about the differences in `puf.csv` variables caused by this pull request.  First a summary of the findings, then a copy of the `compare.py` script, and finally, `compare.res` that contains the results generated by the script.

#### Summary
```
$ python compare.py > compare.res

$ head compare.res 
VAR,TOTAL,DIFFS= p23250 187123 0
VAR,TOTAL,DIFFS= p25470 187123 0
SKIPPED-VAR: ftpt_spouse
VAR,TOTAL,DIFFS= e09800 187123 0
VAR,TOTAL,DIFFS= RECID 187123 0
VAR,TOTAL,DIFFS= e01400 187123 0
SKIPPED-VAR: num_ss
VAR,TOTAL,DIFFS= e02000 187123 383
VAR,TOTAL,DIFFS= e62900 187123 0
VAR,TOTAL,DIFFS= e03300 187123 0

$ awk '{n++}END{print n}' compare.res
148
# ==> 148 variables in both old and new puf.csv files

$ awk '$1~/SKIP/{n++}END{print n}' compare.res
66
# ==> 66 variables in only one of two old and new puf.csv files

$ awk '$1~/DIFF/{n++}END{print n}' compare.res
82
# ==> 82 + 66 = 148

$ awk '$1~/DIFF/{n[$3]++}END{for(i in n)print i,n[i]}' compare.res
187123 82
# ==> number of records with same RECID in both files

$ awk '$1~/DIFF/&&$4>0{d++;print $2,$4}END{print d}' compare.res
e02000 383
e00200 222
elderly_dependent 20
e02400 5121
XTOT 3091
e01700 1456
e00800 192
age_spouse 171637
e00300 2484
e02100 23
age_head 181480
e00900 178
e02100s 4365
e02100p 4385
nu13 25043
MARS 2825
e00900p 23369
e00900s 23193
e00200p 65988
e00200s 65895
nu05 11317
e02300 176
s006 109055
e00600 712
24
# ==> 24 variables have different values among the 187123 records that have same RECID
# ==> some of these variables have just a few differences; others have many differences
# ==> most of the variables that have many differences are imputed using random numbers
```

#### compare.py
```
import sys
import numpy as np
import pandas


FILE1 = 'puf-prepr83.csv'
FILE2 = 'puf.csv'
EPSILON = 1e-3
DUMP = False


def main():
    """
    Compares values of each variable present in both FILE1 and FILE2.
    """
    df1 = pandas.read_csv(FILE1)
    df1.set_index('RECID', drop=False, inplace=True, verify_integrity=True)
    df2 = pandas.read_csv(FILE2)
    df2.set_index('RECID', drop=False, inplace=True, verify_integrity=True)
    df1_vars = set(list(df1))
    df2_vars = set(list(df2))
    all_vars = df1_vars | df2_vars
    recid_list = df1['RECID'].tolist()
    recid_warnings = list()
    for var in all_vars:
        if var in df1_vars and var in df2_vars:
            ntotal = 0
            ndiffs = 0
            for rid1 in recid_list:
                val1 = df1[var][rid1]
                try:
                    val2 = df2[var][rid1]
                except:
                    if rid1 not in recid_warnings:
                        recid_warnings.append(rid1)
                        if DUMP:
                            print 'NO-FILE2-RECID {}'.format(rid1)
                    continue  # to next row
                ntotal += 1
                if abs(val1 - val2) > EPSILON:
                    ndiffs += 1
                    if DUMP:
                        print 'VAR,RECID,VAL1,VAL2= {} {} {} {}'.format(var,
                                                                        rid1,
                                                                        val1,
                                                                        val2)
            print 'VAR,TOTAL,DIFFS= {} {} {}'.format(var, ntotal, ndiffs)
        else:
            print 'SKIPPED-VAR: {}'.format(var)
    return 0
# end of main function code


if __name__ == '__main__':
    sys.exit(main())
```

#### compare.res
```
VAR,TOTAL,DIFFS= p23250 187123 0
VAR,TOTAL,DIFFS= p25470 187123 0
SKIPPED-VAR: ftpt_spouse
VAR,TOTAL,DIFFS= e09800 187123 0
VAR,TOTAL,DIFFS= RECID 187123 0
VAR,TOTAL,DIFFS= e01400 187123 0
SKIPPED-VAR: num_ss
VAR,TOTAL,DIFFS= e02000 187123 383
VAR,TOTAL,DIFFS= e62900 187123 0
VAR,TOTAL,DIFFS= e03300 187123 0
SKIPPED-VAR: snap_participation
SKIPPED-VAR: ftpt_head
SKIPPED-VAR: num_snap
SKIPPED-VAR: snap
VAR,TOTAL,DIFFS= e00200 187123 222
VAR,TOTAL,DIFFS= elderly_dependent 187123 20
VAR,TOTAL,DIFFS= p08000 187123 0
SKIPPED-VAR: e52872
VAR,TOTAL,DIFFS= e58990 187123 0
SKIPPED-VAR: hga_spouse
SKIPPED-VAR: ssi
VAR,TOTAL,DIFFS= e00700 187123 0
SKIPPED-VAR: snap_participationp
SKIPPED-VAR: snap_participations
SKIPPED-VAR: num_vet
VAR,TOTAL,DIFFS= e26270 187123 0
VAR,TOTAL,DIFFS= e02400 187123 5121
VAR,TOTAL,DIFFS= e03270 187123 0
SKIPPED-VAR: jcps25
SKIPPED-VAR: medicarex_dep
VAR,TOTAL,DIFFS= XTOT 187123 3091
VAR,TOTAL,DIFFS= e17500 187123 0
VAR,TOTAL,DIFFS= e03290 187123 0
VAR,TOTAL,DIFFS= e07240 187123 0
VAR,TOTAL,DIFFS= e01700 187123 1456
VAR,TOTAL,DIFFS= e00800 187123 192
VAR,TOTAL,DIFFS= age_spouse 187123 171637
VAR,TOTAL,DIFFS= agi_bin 187123 0
VAR,TOTAL,DIFFS= e19200 187123 0
SKIPPED-VAR: hga_head
VAR,TOTAL,DIFFS= e27200 187123 0
SKIPPED-VAR: age_dep5
SKIPPED-VAR: age_dep4
SKIPPED-VAR: cpsseq
SKIPPED-VAR: age_dep1
SKIPPED-VAR: age_dep3
SKIPPED-VAR: age_dep2
SKIPPED-VAR: ssip
VAR,TOTAL,DIFFS= e00300 187123 2484
VAR,TOTAL,DIFFS= e02100 187123 23
SKIPPED-VAR: gender_head
VAR,TOTAL,DIFFS= e19800 187123 0
VAR,TOTAL,DIFFS= e01200 187123 0
VAR,TOTAL,DIFFS= e00400 187123 0
VAR,TOTAL,DIFFS= e03500 187123 0
SKIPPED-VAR: wt
VAR,TOTAL,DIFFS= DSI 187123 0
SKIPPED-VAR: prodseq
SKIPPED-VAR: n1821
SKIPPED-VAR: age_youngest
SKIPPED-VAR: ssi_dep
SKIPPED-VAR: e07140
SKIPPED-VAR: vbs
SKIPPED-VAR: vbp
VAR,TOTAL,DIFFS= e03210 187123 0
VAR,TOTAL,DIFFS= e07260 187123 0
SKIPPED-VAR: p86421
SKIPPED-VAR: snaps
VAR,TOTAL,DIFFS= FLPDYR 187123 0
SKIPPED-VAR: age_oldest
VAR,TOTAL,DIFFS= e00650 187123 0
VAR,TOTAL,DIFFS= age_head 187123 181480
SKIPPED-VAR: ssis
VAR,TOTAL,DIFFS= e00900 187123 178
VAR,TOTAL,DIFFS= p22250 187123 0
SKIPPED-VAR: medicarexs
SKIPPED-VAR: num_ssi
VAR,TOTAL,DIFFS= e03220 187123 0
VAR,TOTAL,DIFFS= n24 187123 0
VAR,TOTAL,DIFFS= e07400 187123 0
VAR,TOTAL,DIFFS= e02100s 187123 4365
VAR,TOTAL,DIFFS= filer 187123 0
VAR,TOTAL,DIFFS= e02100p 187123 4385
VAR,TOTAL,DIFFS= f2441 187123 0
SKIPPED-VAR: SOISEQ
SKIPPED-VAR: num_medicare
SKIPPED-VAR: h_seq
VAR,TOTAL,DIFFS= nu13 187123 25043
SKIPPED-VAR: nu18
VAR,TOTAL,DIFFS= f6251 187123 0
SKIPPED-VAR: snap_dep
VAR,TOTAL,DIFFS= e03230 187123 0
VAR,TOTAL,DIFFS= e03400 187123 0
VAR,TOTAL,DIFFS= e18500 187123 0
SKIPPED-VAR: peridnum
VAR,TOTAL,DIFFS= e20400 187123 0
SKIPPED-VAR: ss
SKIPPED-VAR: head_age
VAR,TOTAL,DIFFS= e07300 187123 0
VAR,TOTAL,DIFFS= MARS 187123 2825
SKIPPED-VAR: sp_ptr
VAR,TOTAL,DIFFS= e00900p 187123 23369
VAR,TOTAL,DIFFS= e00900s 187123 23193
VAR,TOTAL,DIFFS= e00200p 187123 65988
SKIPPED-VAR: vb
VAR,TOTAL,DIFFS= e00200s 187123 65895
SKIPPED-VAR: medicarex
SKIPPED-VAR: gender_spouse
SKIPPED-VAR: spouse_age
VAR,TOTAL,DIFFS= e11200 187123 0
VAR,TOTAL,DIFFS= e24518 187123 0
VAR,TOTAL,DIFFS= EIC 187123 0
SKIPPED-VAR: num_medicaid
VAR,TOTAL,DIFFS= e09700 187123 0
VAR,TOTAL,DIFFS= nu05 187123 11317
VAR,TOTAL,DIFFS= p87521 187123 0
VAR,TOTAL,DIFFS= e09900 187123 0
VAR,TOTAL,DIFFS= e24515 187123 0
SKIPPED-VAR: jcps28
VAR,TOTAL,DIFFS= e01500 187123 0
VAR,TOTAL,DIFFS= e03240 187123 0
VAR,TOTAL,DIFFS= e02300 187123 176
SKIPPED-VAR: vb_participations
SKIPPED-VAR: vb_participationp
VAR,TOTAL,DIFFS= e87530 187123 0
VAR,TOTAL,DIFFS= e03150 187123 0
SKIPPED-VAR: ssi_participation
SKIPPED-VAR: snapp
VAR,TOTAL,DIFFS= e20100 187123 0
SKIPPED-VAR: e52852
VAR,TOTAL,DIFFS= e07600 187123 0
VAR,TOTAL,DIFFS= cmbtp 187123 0
SKIPPED-VAR: jcps35
SKIPPED-VAR: ssi_participationp
SKIPPED-VAR: ssi_participations
VAR,TOTAL,DIFFS= s006 187123 109055
SKIPPED-VAR: medicaid
SKIPPED-VAR: n21
SKIPPED-VAR: jcps38
SKIPPED-VAR: medicarexp
VAR,TOTAL,DIFFS= e00600 187123 712
VAR,TOTAL,DIFFS= e18400 187123 0
SKIPPED-VAR: finalseq
VAR,TOTAL,DIFFS= e20500 187123 0
SKIPPED-VAR: i
VAR,TOTAL,DIFFS= e32800 187123 0
VAR,TOTAL,DIFFS= e01100 187123 0
VAR,TOTAL,DIFFS= MIDR 187123 0
```

@MattHJensen @Amy-Xu @andersonfrailey

**Pull request merged**
