### PR TITLE
Add a_lineno to CPS

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR completes @evtedeschi3's request to include `a_lineno` in the CPS file. This replaces previous TaxData and Tax-Calculator PR's that added `FHEADIDX`. I'll open a corresponding Tax-Calculator PR shortly.

cc @MattHJensen

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey,  What exactly is the `a_lineno` variable?  Is it a line number for CPS household records, family records, or person records?

**Comment by andersonfrailey** [comment]
@martinholmer, `a_lineno` is the line number for the CPS person record of the head of the tax unit.

Also, last commit fixed the issue I mentioned in our conversation. The CPS file in this PR is ready for Tax-Calculator now.

**Comment by martinholmer** [comment]
@andersonfrailey,  Here is what we have now in `records_variables.json`:
```
    "a_lineno": {
      "type": "int",
      "desc": "CPS ????????? (not used in tax-calculation logic)",
      "form": {"2013-2016": "sample construction info"},
      "availability": "taxdata_cps"
    },
    "ffpos": {
      "type": "int",
      "desc": "CPS family identifier within household (not used in tax-calculation logic)",
      "form": {"2013-2016": "sample construction info"},
      "availability": "taxdata_cps"
    },
```

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for the variable definition.

**Comment by martinholmer** [comment]
@andersonfrailey,  Everything look good in T-C PR #1885, so go ahead and merge PR #152.  Thanks.

**Pull request merged**
