### PR TITLE
extrapolate CPS benefits

### PR DESCRIPTION
**Pull request by hdoupe**
This script extrapolates participation and benefits for welfare programs as discussed in issue #106.

This PR is a WIP and still needs to be augmented so that it can handle other types of benefits besides SSI.

cc @Amy-Xu

### CODE REVIEW

**Comment by Amy-Xu** [comment]
I think it worth a bit time to see where is the best place for this extrapolation routine script. @martinholmer @andersonfrailey 

But that's  not a high priority at the moment.

**Comment by andersonfrailey** [comment]
Bringing this back up, I think the best option is to keep this extrapolation routine in a `cps_stage3` folder. This way we can run everything in `cps_data` to create the raw CPS tax unit file, then create the weights using code in the `cps_stage2` folder, then run benefit extrapolation, then clean up the CPS file so that it's ready for Tax-Calculator.

**Comment by andersonfrailey** [comment]
I'm also working on extending the extrapolation to include 2027 now that we have that capability.

**Comment by andersonfrailey** [comment]
>I'm also working on extending the extrapolation to include 2027 now that we have that capability.

Scratch that. We can only extrapolate to 2027 with the PUF file, not the CPS. Mental lapse on my part

**Comment by martinholmer** [comment]
@andersonfrailey said:
> We can only extrapolate to 2027 with the PUF file, not the CPS. 

Can you explain why that is the case?  Does the benefit extrapolation only go thru 2026?

If so, is this going to cause a problem in Tax-Calculator?  
How is Tax-Calculator going to handle input data sets with two different last years?

@MattHJensen @Amy-Xu

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>Can you explain why that is the case? Does the benefit extrapolation only go thru 2026?

This is because the weights file we have for the CPS only goes to 2026. John gave us the code he used to create the file, but not the code to create the weights file so I can't generate a new one that goes to 2027 on my own.

As part of PR #118, I'm working on a script to create an accompanying weights file, but it isn't complete yet.

I haven't given too much thought to how this would affect Tax-Calculator. I'd imagine if you were to try and run Tax-Calculator to 2027 using the CPS you would get an error that the specified column in the weights file doesn't exist.

I will also email John to see if he has a new weights file available to goes to 2027.

**Comment by andersonfrailey** [comment]
Now that the merge conflict has been resolved, I'm planning on merging this PR tomorrow unless there are additional comments.

**Comment by Amy-Xu** [comment]
Thanks Anderson!

**Pull request merged**
