### PR TITLE
Add AIPD to stage1.py

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR addresses issue #65. It adds interest paid deduction amounts to `SOI_estimates` as `IPD` and calculates AIPD in `stage1.py`. While working on this PR I noticed I made a mistake in calculating AIPD in the last update to `Stage_I_factors`. I mistakenly thought that AIPD was previously calculated using the growth rate of `ATXPY` in whatever the last year of `SOI_estimates`. After taking another look at TaxCalc PR [#231](https://github.com/open-source-economics/Tax-Calculator/pull/231) I realized my mistake and this PR contains the proper formula for AIPD. After this PR is merged, I will need to open on in TaxCalc so `growthfactors.csv` is correct.

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey, Thanks for the contribution in taxdata pull request #67, but I'm confused about a couple of things.

(1) Can you explain exactly what you think your earlier AIPD mistake was?  What did you do before and what are you doing now and what in [Tax-Calculator PR 231](https://github.com/open-source-economics/Tax-Calculator/pull/231) made you think you made a mistake?

(2) So, if you did make a mistake before, I can see why the values of AIPD generated by this pull request would differ from the AIPD values in the Tax-Calculator `growfactors.csv` file.  But what I don't understand is why the values of AWAGE are changing in every year.  What's going on there?  You've not said anything about those being wrong in earlier taxdata releases.

(3) Including AIPD in the `Stage_II_targets.csv` file has no effect on the stage2 weight calculations, right?  If so, why include AIPD in the `Stage_II_targets.csv` file?

**Comment by andersonfrailey** [comment]
@martinholmer 
> (1) Can you explain exactly what you think your earlier AIPD mistake was? What did you do before and what are you doing now and what in Tax-Calculator PR 231 made you think you made a mistake?

I made a spreadsheet error when calculating AIPD previously. Looking back at what @Amy-Xu said in #231, there were two steps to creating AIPD (I've updated her comments to make the years fit):
1. Using 2009 as the base year, find the growth of interest paid deduction until 2014, the last year total interest paid is available in the tax data. This results in AIPD for 2009-2014.
2. Apply the growth rate of ATXPY to 2014 AIPD to generate values for 2015 on.

What I mistakenly did was apply 2014 ATXPY to `AIPDy-1` to get `AIPDy`.

I confirmed my mistake by downloading `StageIfactors.csv` from #231 and reproducing AIPD from that. This PR is designed to correctly calculate AIPD.

> But what I don't understand is why the values of AWAGE are changing in every year. What's going on there? You've not said anything about those being wrong in earlier taxdata releases.

I'm assuming this is in reference to the commit `fix AWAGE`. There is nothing wrong with the values of AWAGE in previous tax data releases. Because I added interest paid deduction to `SOI_estimates.csv` in order to calculate AIPD the columns used to calculate total wage and subsequently AWAGE were changed.

This is the section of code at issue:
```python
data = Stage_II_targets[Stage_II_targets.columns[19:31]].sum(axis=1)
total_wage = pd.DataFrame(data, columns=['AWAGE'])
```
Before that commit this read:
```python
data = Stage_II_targets[Stage_II_targets.columns[18:30]].sum(axis=1)
total_wage = pd.DataFrame(data, columns=['AWAGE'])
```
This was needed because, for purely personal aesthetic reasons, I added the interest paid deduction numbers above wage 1-12 in `SOI_estimates.csv`, throwing off the calculation of AWAGE. This commit kept the values of AWAGE from changing from what they currently are.

> (3) Including AIPD in the Stage_II_targets.csv file has no effect on the stage2 weight calculations, right? If so, why include AIPD in the Stage_II_targets.csv file?

Correct. IPD ended up in the Stage_II_targets.csv file because I added interest paid deduction to `SOI_estimates.csv` and ultimately the `Stage_II_targets` data frame so that the lines of code used to create AIPD would look like all the others. This could be dropped without consequence.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Correct. IPD ended up in the `Stage_II_targets.csv` file because I added interest paid deduction to `SOI_estimates.csv` and ultimately the Stage_II_targets data frame so that the lines of code used to create AIPD would look like all the others. This could be dropped without consequence.

Why not drop it just before writing the `Stage_II_targets.csv` file?

**Comment by martinholmer** [comment]
@andersonfrailey said:
> ... This commit kept the values of AWAGE from changing from what they currently are.

That is the correct intent, but they DID change.  Look on GitHub at "Files changed" for PR #67 and you will see that the `stage1/growfactors.csv` file not only has the AIPD values added onto the end of each year row, but also has big changes in the values for AWAGE.  For example, AWAGE in 2013 on the master branch is 1.019855 and it is 1.028595 in your pull request.  That's a big difference: 2.9% versus the old 2.0% value.  My question is simply why do all the AWAGE values in the `stage1/growfactors.csv` file change when all you are trying to do is add values for AIPD.

**Comment by andersonfrailey** [comment]
@martinholmer 
>Why not drop it just before writing the Stage_II_targets.csv file?
Dropped in latest commit.

I figured out the problem with AWAGE. I must have just not run the `stage1.py` until after pushing so what you saw were the incorrect values produced before I corrected the column index used to find AWAGE. Corrected in latest commit.

**Comment by martinholmer** [comment]
@andersonfrailey, PR #67 looks such better now.  I'm going to download #67 on my computer and develop a bash script that works through the stages doing everything in the correct order.  Seems like our recent experience shows the worth of a script like this.  Once I can replicate the results in PR #67, I'll merge it (probably later this afternoon).

**Pull request merged**
