### PR TITLE
Add FHEADIDX Variable to CPS

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR completes a request from @evtedeschi3 and @MattHJensen to add the `fheadidx` variable onto the CPS.

It also updates all the SAS files necessary. Many of the changes have to do with line spacing that gets a little wonky when transferring the SAS files from our server to my local machine so that I can add them to the PR. The other changes are either directly related to this PR, or for past PR's in which I forgot to copy the SAS files from the server and add them to the PR.

### CODE REVIEW

**Comment by evtedeschi3** [comment]
Was this delayed? I just checked my CPS output under Tax-Calculator 0.16 and did not see this variable.

**Comment by andersonfrailey** [comment]
@evtedeschi3, yes. The Tax-Calculator PR corresponding with this one was closed without merging. Per my last comment in that PR, is `A-LINENO` the variable you're looking for, rather than `PULINENO`?

**Comment by evtedeschi3** [comment]
Yes, A-LINENO should be exactly the one.

**Comment by andersonfrailey** [comment]
Great. I'll close this PR and open a new one that includes A-LINENO in the CPS file.

**Pull request closed without merging**
