### PR TITLE
Add SAS Files

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR addresses issue #77. It adds the SAS files used in the statistical matching process and some documentation.

@MattHJensen @martinholmer @Amy-Xu

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey said:
> This PR addresses issue #77.
> It adds the SAS files used in the statistical matching process and some documentation.

I don't understand why a free-standing taxdata/StatMatch directory has been created when, keeping with the style of the repo, we should have put these SAS scripts in the taxdata/puf_data/doc directory.  Aren't these SAS scripts that programs that created the `taxdata/puf_data/cps-matched-puf.csv` file?  If so, then they document the creation of that file, so shouldn't they be in the taxdata/puf_data/doc directory?

**Comment by andersonfrailey** [comment]
@martinholmer, good point. Moved.

**Comment by MattHJensen** [comment]
@martinholmer @andersonfrailey, what's the plan for the imputation and augmentation scripts for the CPS-based file? Would they similarly go in a `cps_data/doc` directory?

**Comment by martinholmer** [comment]
@MattHJensen asked:
> what's the plan for the imputation and augmentation scripts for the CPS-based file? Would they similarly go in a cps_data/doc directory?

Probably.  If they are Python scripts maybe they are part of the `csvmake` work flow, and are, therefore, not documentation but scripts that are executed.  What is the starting point in making `cps.csv`?  Is their a raw csv-formatted CPS file that serves as the starting point in the preparation of the final `cps.csv` file?  Is it the `taxdata/cps_data/prod2015_v2e.csv` file that is read into the `cps-processing.py` script?  Where is that file now?

@andersonfrailey

**Comment by andersonfrailey** [comment]
@martinholmer @MattHJensen,

I talked to John about his progress on the CPS based file on Thursday and he's writing the scripts to make it in SAS. The CPS file being used as a starting point can be download from NBER's website right now, but it is in a `.dat` format, not `.csv`.

>Is their a raw csv-formatted CPS file that serves as the starting point in the preparation of the final cps.csv file? Is it the taxdata/cps_data/prod2015_v2e.csv file that is read into the cps-processing.py script?

`prod2015_v2e.csv` is a preliminary version of the file John is creating from that original CSV file. I have a copy of that file in my Dropbox account.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> I talked to John about his progress on the CPS based file on Thursday and he's writing the scripts to make it in SAS.  The CPS file being used as a starting point can be download from NBER's website right now, but it is in DAT format, not in CSV format.
>
> `prod2015_v2e.csv` is a preliminary version of the file John is creating from that original CSV file.
> I have a copy of that file in my Dropbox account.

Thanks for the helpful information, @andersonfrailey.  Did you mean to say the following?
> `prod2015_v2e.csv` is a preliminary version of the file John is creating from that original DAT file.

If the `prod2015_v2e.csv` file is not simply as traslation from DAT format to CSV format, then I'm confused.  Please clarify.  Thanks.

**Comment by MattHJensen** [comment]
> Maybe. But if they are Python scripts maybe they are part of the csvmake work flow, and are, therefore, not documentation but scripts that are executed. 

Thanks @martinholmer. It makes sense to me to draw a distinction between the .sas files that can not be executed and the Python files that can be.

**Comment by andersonfrailey** [comment]
@martinholmer 
>If the prod2015_v2e.csv file is not simply as traslation from DAT format to CSV format, then I'm confused. Please clarify. Thanks.

`prod2015_v2e.csv` is not a translation from DAT format to CSV. The DAT file is a completely unprocessed version of the CPS and contains records at household, family, and personal levels.

`prod2015_v2e.csv` is the result of taking the DAT file and combining the household, family, and personal records to create tax unit records that are usable in TaxCalc, as well as adding a few imputed variables. The reason this file needs to be cleaned up with the `cps_processing.py` script is that there are a number of unnecessary variables that were added on during it's creation process that need to be dropped and a few that can be used to impute more variables.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> `prod2015_v2e.csv` is not just a translation from DAT format to CSV format. The DAT file is a completely unprocessed version of the CPS and contains records at household, family, and personal levels.
>
> `prod2015_v2e.csv` is the result of taking the DAT file and combining the household, family, and personal records to create tax unit records that are usable in TaxCalc, as well as adding a few imputed variables. The reason this file needs to be cleaned up with the cps_processing.py script is that there are a number of unnecessary variables that were added on during it's creation process that need to be dropped and a few that can be used to impute more variables.

@andersonfrailey, Thanks for the helpful explanation.  So, if I understand correctly, the `cps_data/prod2015_v2e.csv` file is exactly analogous to the `puf_data/cps-matched-puf.csv` file in the sense that it needs only some final preparation, right?  If so, why don't you rename the `cps_data/cps-processing.py` script as `cps_data/finalprep.py` so that the `csvmake` script will work correctly?  And then, put the SAS files that constructed `prod2015_v2e.csv` in the cps_data/doc directory.  Does that make sense?

@MattHJensen

**Comment by andersonfrailey** [comment]
@martinholmer 
>If so, why don't you rename the cps_data/cps-processing.py script as cps_data/finalprep.py so that the csvmake script will work correctly? And then, put the SAS files that constructed prod2015_v2e.csv in the cps_data/doc directory.

Makes sense to me. I don't have the SAS files that constructed `prod2015_v2e.csv` right now, but I can add them when I do.

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for taxdata pull request #78.  Looks good.  I'm merging it now.

**Pull request merged**
