### PR TITLE
CBO_baseline update 2027 projection

### PR DESCRIPTION
**Pull request by Jennydeng123**
In the CBO_baseline projection, 

Following Variables are from the 10-Year Economic Projections (CBO) 
Link: https://www.cbo.gov/about/products/budget-economic-data#4 
Previous: August 2016 
Current: June 2017
Notes: These are pulled directly from the corresponding file 

   GDP     : GDP 
   TPY      : Income, Personal 
   Wages : Wages and salaries 
   SCHC   : Proprietors Income, Non Farm with IVA & CCAdj 
   SCHF    : Proprietors Income, Farm with IVA & CCAdj 
   INTS     : Interest Income, Personal 
   DIVS     : Dividend Income, Personal 
   RENTS  : Income, Rental, with CCAdj 
   BOOK   : Profits, Corporate with IVA & CCAdj 
   CPIU     : Consumer Pricing Index, All Urban Consumers (CPI-U) 

Variables not in 10-year CBO Economic Projections:

   CGNS  : Source: Detailed Revenue Projections (CBO) 
                Link: https://www.cbo.gov/about/products/budget-economic-data#7 
                Previous: January 2016 
                Current: January 2017 
   Notes  : In the revenue projections file, the data is in the 'Capital Gains Realizations'
                 tab under the 'Capital Gains Realizations' column. 

    RETS   : Source: IRS Publication 6187, Table 1B 
                 Link: https://www.irs.gov/pub/irs-soi/Pub6187.pdf
                 Previous: Publication 6187, Fall 2016          
                 Current: Publication 6187, Fall 2017          
    Notes  : Years 2016 to 2024 are directly from the table. Years 2025 to 2027 are
                  extrapolated out using the growth rate between 2024 and 2023. 

SOCSEC  : Source: OASI Trust Fund Annual Trustees Report -Table VI.C4: Operations 
                 of the OASI Trust Fund, Fiscal Years 2011-15. 
                 Column: Cost: Scheduled Benefits: Intermediate Level 
                 Link: https://www.ssa.gov/oact/tr/2017/index.html                 
                 Previous: 2016 report 
                 Current: 2017 report 
     Notes : Projections are taken directly from this chart. 
                 The 2017 value is imputed using the growth rate from 2025-2026

    CPIM  : Source: BLS Database 
                 Link: https://data.bls.gov/cgi-bin/surveymost?cu                  
                 Current: CPIU Data Series ID CUUR0000SA0 
                               CPIM Data Series ID CUUR0000SAM 
                 Instructions: 
                 - Look at the medical care component of CPI-Urban Consumers 
                 - Choose the annual average from year 2008-2016 in the data 
                 - Find the difference of the annual average between CPI-U and
                    CPI Medical Care during these years
                 - take an average of all these differences for those years
                 - Add this average difference to the CBO CPI-U projections 

 UCOMP : Source: CBO Unemployment Compensation Projections 
                 Link: https://www.cbo.gov/about/products/baseline-projections-selected-programs#24 
                 Previous: March 2016 
                 Current: June 2017 
      Notes : Put the 'Total Benefits' number from the table in terms of 
                   billions rather than millions of dollars 

For stage1.py : 
Increase year in the for loop to be one greater than the previous one, i.e., from 2026 to 2027, or from 2027 to 2028.

I do not update the 'CLP_solver_16Years.py'

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Thanks @Jennydeng123 ! I'll look this over.

**Comment by andersonfrailey** [comment]
@Jennydeng123, thanks for getting this started. The work in this PR has been continued in #122.

**Comment by MattHJensen** [comment]
@Jennydeng123 thanks for the contribution! Just fyi, your individual commits live on in #122 and will be in the project history forever once that is merged.

**Comment by Jennydeng123** [comment]
@MattHJensen @andersonfrailey You are welcome! I am more than happy to help!

**Pull request closed without merging**
