### PR TITLE
Remove four more unused variables from puf.csv file

### PR DESCRIPTION
**Pull request by martinholmer**
This taxdata-repository pull request removes four additional variables from the `puf.csv` input file used by Tax-Calculator and TaxBrain.  These four variables are no longer used in Tax-Calculator logic, and therefore, are completely redundant.  A Tax-Calculator-repository pull request will be prepared that matches this one by dropping these four variables from the `Records.VALID_READ_VARS` set.  Once that pull request is merged, only the smaller `puf.csv` file generated by this pull request will work with Tax-Calculator.

@MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

### CODE REVIEW

**Comment by Amy-Xu** [comment]
Thanks Martin! Merging.

**Comment by martinholmer** [comment]
@Amy-Xu,  Thanks for the quick attention to taxdata pull request #36.

**Comment by talumbau** [comment]
@Amy-Xu are you going to send a link to the dropbox with the new PUF?

**Comment by feenberg** [comment]
What is new about the new PUF?

dan

**Comment by martinholmer** [comment]
Dan @feenberg asked:
> What is new about the new PUF?

Four fewer variables; otherwise no changes.  The removed variables are not being used in Tax-Calculator logic, so they are redundant.

**Comment by Amy-Xu** [comment]
T.J., yep going to send it out today.

**Pull request merged**
