### PR TITLE
Add k1bx14p and k1bx14s to puf.csv file

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request changes the logic of splitting the `e00900` (Schedule C) and `e02100` (Schedule F) self-employment earnings variables and adds new `k1bx14p` and `k1bx14s` variables that are part of self-employment income taxable under the SECA tax (Schedule SE).

These taxdata changes, along with the changes in [Tax-Calculator pull request 1438](https://github.com/open-source-economics/Tax-Calculator/issues/1438), are meant to resolve the Tax-Calculator bug described in [Tax-Calculator issue 1436](https://github.com/open-source-economics/Tax-Calculator/issues/1436).

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey,  I know you're busy with the CPS file preparation, but I'm hoping you can help me issue a new version of the `puf.csv` file in the next day or so.  @MattHJensen has approved this timing of the new `puf.csv` release, so all you need to do is review taxdata pull request #107 to make sure the logic changes in the `puf_data/finalprep.py` script make sense and confirm that you get the same new `puf.csv` on your computer as I'm getting on my computer.

Using pull request #107, I get the following information about the new `puf.csv` file:
```
iMac2:taxdata mrh$ cd puf_data

iMac2:puf_data mrh$ ls -l | grep puf
-rw-r--r--@ 1 mrh  staff  178345362 Mar 21 13:33 cps-matched-puf-20170321.csv
-rw-r--r--@ 1 mrh  staff  205020518 Jun 13 14:19 cps-matched-puf-20170613.csv
-rw-r--r--@ 1 mrh  staff  205020518 Jun 13 14:19 cps-matched-puf.csv

iMac2:puf_data mrh$ md5 cps-matched-puf.csv 
MD5 (cps-matched-puf.csv) = 0f022b56fea4d93343cbace54269f3ed

iMac2:puf_data mrh$ git branch
* add-k1bx14
  master

iMac2:puf_data mrh$ python finalprep.py 

iMac2:puf_data mrh$ ls -l puf.csv
-rw-r--r--  1 mrh  staff   53743252 Jul  5 11:27 puf.csv

iMac2:puf_data mrh$ md5 puf.csv 
MD5 (puf.csv) = ca0ad8bbb05ee15b1cbefc7f1fa1f965
```

Do you get the same MD5 checksums for input file `cps-matched-puf.csv` and output file `puf.csv` on your computer?

@Amy-Xu @hdoupe

**Comment by andersonfrailey** [comment]
Sorry for missing this, @martinholmer.

I get the same MD5 checksums for both the input and output files as you do:
```
Anderson-Frailey-MacBook-Pro:puf_data andersonfrailey$ md5 cps-matched-puf.csv
MD5 (cps-matched-puf.csv) = 0f022b56fea4d93343cbace54269f3ed
Anderson-Frailey-MacBook-Pro:puf_data andersonfrailey$ md5 puf.csv
MD5 (puf.csv) = ca0ad8bbb05ee15b1cbefc7f1fa1f965
Anderson-Frailey-MacBook-Pro:puf_data andersonfrailey$ 
```

You're logic in this PR also looks good to me given its goal.

Unless there is more you would like to add, I'll merge this PR and distribute the new PUF this afternoon.

**Comment by martinholmer** [comment]
@andersonfrailey said about taxdata pull request #107:
> Unless there is more you would like to add, I'll merge this PR and distribute the new PUF this afternoon.

That would be excellent!  Thanks for the help.

**Comment by andersonfrailey** [comment]
Merged #107

**Pull request merged**
