### PR TITLE
Documentation on updating the CBO baseline and SOI Estimates files

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR simply adds a text file with instructions on how to update the `CBO_Baseline.csv` file found in the Stage I folder. The instructions were made from notes I took while updating the file.

The file specifies the current year of the reports/files where the numbers in `CBO_Baseline` come from. This is with regard to the fully updated file, which has not been uploaded yet, not the file currently on GitHub. I want to wait and upload that after I make sure it works with everything else.

CC: @Amy-Xu @MattHJensen

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Latest commit add new information to the CBO update documentation and adds documentation for updating `SOI_estimates.csv`. I've changed the title of this PR to reflect this additional document.

**Comment by Amy-Xu** [comment]
@andersonfrailey Is this all you want to do in this PR? If so, I can merge it now. It looks good to me. Although I feel it's pretty tricky to update stage_I.py and the stage II scripts, this is a good starting point.

**Comment by andersonfrailey** [comment]
@Amy-Xu that's all for now. I'll make more detailed notes on updating stage_I.py and stage II as I update them myself.

**Comment by Amy-Xu** [comment]
Thanks for the updates. Could you actually replace xlsx with CSV or txt format? xlsx is not quite compatible with github. We couldn't utilize any diff-tracking functions either.

**Comment by andersonfrailey** [comment]
@Amy-Xu changed to CSV.

**Comment by Amy-Xu** [comment]
Thanks Anderson!

**Pull request merged**
