### PR TITLE
Add num dep under 18

### PR DESCRIPTION
**Pull request by hdoupe**
This feature estimates the number of dependents under the age of 18 in order to address [Tax-Calculator issue #1409](https://github.com/open-source-economics/Tax-Calculator/issues/1409).

### CODE REVIEW

**Comment by martinholmer** [comment]
@hdoupe,  Even though I've read over [Tax-Calculator issue #1409](https://github.com/open-source-economics/Tax-Calculator/issues/1409), I'm still having difficultly following what you are doing in the taxdata code you're proposing to add in pull request #93.  Can you add some comments to your pull request that explain what the new code does?  

Also, why name the new variable `nu18_dep`?  Why not just `nu18`?  Isn't that the way the other analogous variables are named?

@MattHJensen @andersonfrailey

**Comment by martinholmer** [comment]
@hdoupe,  I strongly suggest that you put your proposed code and comment in a new function.

@MattHJensen @andersonfrailey

**Comment by hdoupe** [comment]
@martinholmer Thank you for your input.  I moved my code into a new function and added comments to better explain what the code does.  

`nu18` is already a variable and it counts the number of individuals under 18 years old in a tax unit.  I used `nu18_dep` to emphasize that this variable  counts the number of dependents under the age of 18.

**Comment by martinholmer** [comment]
@hdoupe said:
> `nu18` is already a variable and it counts the number of individuals under 18 years old in a tax unit. I used `nu18_dep` to emphasize that this variable counts the number of dependents under the age of 18.

Oh.  How many of the `nu18` are not in `nu18_dep`?
I wasn't aware that we made such a distinction.
Why would there be non-dependent members of a filing unit?
Doesn't the term "filing unit" strongly suggest all members of the filing unit are dependents?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey

**Comment by hdoupe** [comment]
@martinholmer, for 97% of tax units these variables are the same.  But there are some cases where they differ.  Just looking through the code, there could be an independent filer who is under 18 or a spouse under 18 who isn't a dependent.  I treated `nu18_dep` the same way that `nu05` and `nu13` are treated.  

Here is the breakdown: 
image

@MattHJensen @feenberg @Amy-Xu @andersonfrailey

**Comment by martinholmer** [comment]
@hdoupe said:
> for 97% of tax units these variables are the same. But there are some cases where they differ. Just looking through the code, there could be an independent filer who is under 18 or a spouse under 18 who isn't a dependent. I treated `nu18_dep` the same way that `nu05` and `nu13` are treated.

Thanks for the quick tabulation and explanation.

But I'm still puzzled.  What does it mean to be `an independent filer who is under 18 or a spouse under 18 who isn't a dependent`?  Isn't an "independent filer" in his/her own filing unit?
How can a spouse not be a dependent?  If they are married filing separately, the spouse will be in his/her own filing unit.  Sorry to be so dense about this but it doesn't make sense to me.

And what is the weighted count for the three percent?  Are these filing units with relatively large or relatively small sampling weights?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey

**Comment by hdoupe** [comment]
@martinholmer, you're right. It is strange.  I'll let someone with more knowledge in this area weigh in here.

Here's the breakdown after applying the weights:
image

And the code to produce this:
`df[nu18_diff] = df.nu18 - df.nu18_dep

def wt_count():

    vc = df.nu18_diff.value_counts()
    value = vc.index.tolist()
    count = vc.values.tolist()

    wted = []

    for v, c in zip(value, count):
        wts = df.loc[df.nu18_diff == v, 'wt']
        wted.append(wts.sum()*c)

    wted = np.array(wted)
    wted = wted/wted.sum()

    return pd.DataFrame.from_dict({'values': value, 'wted': wted})


if __name__ == '__main__':
    res = wt_count()
`

**Comment by MattHJensen** [comment]
@martinholmer and @hdoupe, 

My understanding is that the primary taxpayer and spouse are not considered dependents of their own tax filing unit. (although they might be a dependent of another tax unit). The layout of 1040 supports this:
image


Here is more info: https://www.irs.gov/publications/p17/ch03.html
image

**Comment by martinholmer** [comment]
@MattHJensen said:
> My understanding is that the primary taxpayer and spouse are not considered dependents of their own tax filing unit. (Although they might be a dependent of another tax unit.) The layout of 1040 supports this.

OK, what's the implication of this for the work @hdoupe is doing in taxdata pull request #93?

Seems like we already have an pretty accurate `nu18_dep` in the existing `nu18` variable.
So, it seems to me we can dispense with #93 and use `nu18` without giving up much accuracy.

This approach seems particularly promising because the new Python-generated `cpi-matched-puf.csv` file will not need the logic in #93 according to @andersonfrailey in #92.  So, why add it now and have to drop it in a week or two?

@feenberg @Amy-Xu

**Comment by MattHJensen** [comment]
> OK, what's the implication of this for the work @hdoupe is doing in taxdata pull request #93?

 I was answering your question, "But I'm still puzzled. What does it mean to be an independent filer who is under 18 or a spouse under 18 who isn't a dependent? Isn't an "independent filer" in his/her own filing unit? How can a spouse not be a dependent?" The implication is that `nu18` is conceptually different from `nu18_dep.`

> Seems like we already have an pretty accurate nu18_dep in the existing nu18 variable.
So, it seems to me we can dispense with #93 and use nu18 without giving up much accuracy.

That makes sense to me given the closeness of `nu18_dep` and `nu18`. @andersonfrailey, are you comfortable with including the `nu18` variable in a  new SAS-generated puf.csv file.

**Comment by martinholmer** [comment]
@MattHJensen said:
> I was answering your question, "But I'm still puzzled. What does it mean to be an independent filer who is under 18 or a spouse under 18 who isn't a dependent? Isn't an "independent filer" in his/her own filing unit? How can a spouse not be a dependent?" 
**The implication is that nu18 is conceptually different from nu18_dep.**

So, you're saying in a married filing jointly filing unit where the spouse is less than 18 years old, the spouse will be included in the `nu18` count but should not be included in the `nu18_dep` count.
Is that correct?  Is that a sensible construction of the `nu18` variable?

**Comment by martinholmer** [comment]
**More about the definition of `nu18`**

The Tax-Calculator `records_variables.json` file contains this:
```
    "nu05": {
      "type": "float",
      "desc": "Number of dependents under 5 years old",
      "form": {"2013-2016": "imputed from CPS data"}
    },
    "nu13": {
      "type": "int",
      "desc": "Number of dependents under 13 years old",
      "form": {"2013-2016": "imputed from CPS data"}
    },
    "nu18": {
      "type": "int",
      "desc": "Number of people under 18 years old in the filing unit",
      "form": {"2013-2016": "imputed from CPS data"}
    },
    "n1821": {
      "type": "int",
      "desc": "Number of people over 18 and under 21 years old in the filing unit",
      "form": {"2013-2016": "imputed from CPS data"}
    },
    "n21": {
      "type": "int",
      "desc": "Number of people 21 years old or older in the filing unit",
      "form": {"2013-2016": "imputed from CPS data"}
    },
```
Given that `nu05` and `nu13` are counts of **dependents**, why isn't `nu18` also a count of dependents?   I guess I forgot why the `nu18`, `n1821` and `n21` variables switched from dependents to people (including young spouses apparently).  Why the difference in definition?

@MattHJensen @Amy-Xu @andersonfrailey @hdoupe

**Comment by hdoupe** [comment]
>    Seems like we already have an pretty accurate nu18_dep in the existing nu18 variable.
    So, it seems to me we can dispense with #93 and use nu18 without giving up much accuracy.

>>That makes sense to me given the closeness of nu18_dep and nu18. @andersonfrailey, are you comfortable with including the nu18 variable in a new SAS-generated puf.csv file.

This makes sense to me, too. In hindsight, I should have checked this before adding the variable in taxdata.  Thanks for reviewing.

@martinholmer @MattHJensen

**Comment by martinholmer** [comment]
@hdoupe said:
> This makes sense to me, too.  In hindsight, I should have checked this before adding the variable in taxdata.  Thanks for reviewing.

Do we need to add any Tax-Calculator code to implement the request in [Tax-Calculator issue 1409](https://github.com/open-source-economics/Tax-Calculator/issues/1409) using `nu18`?

**Comment by hdoupe** [comment]
@martinholmer I think that we just have to subtract `nu18` from `XTOT` when the personal exemption is calculated in the AGI function in `functions.py`.

**Comment by martinholmer** [comment]
Close taxdata pull request #93 since using `nu18` to approximate `nu18_dep`.

**Comment by martinholmer** [comment]
Closing #93

**Comment by martinholmer** [comment]
Close taxdata pull request #93 since using `nu18` to approximate `nu18_dep`.

**Pull request closed without merging**
