### PR TITLE
Improve imputation of age_spouse in puf_data/finalprep.py

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request resolves the problems identified in issue #18.

These changes are being made now because pull requests #83 and #85 require the distribution of a new version of the `puf.csv` file, so it makes sense to roll all these changes together in order to minimize the number of new `puf.csv` releases.

### CODE REVIEW

**Comment by martinholmer** [comment]
Before the changes to the `age_consistency` function in the `puf_data/finalprep.py` script, there were a sizable minority of married-filing-jointly units that had an extreme difference between the head's age and the spouse's age.

Here are some tabulations that illustrate that problem:
```
$ awk -F, 'NR>1&&$11==2{d=$1-$2;print $72,$1,d}' puf.csv | head
3455930 49 -12
3340520 49 -12
3649970 39 5
3234000 44 -1
3532720 37 11
2977640 39 5
3623890 85 84
3623040 39 5
2898720 60 -2
3483490 73 72
```
So, out of the first ten married filing units (MARS is variable 11 in the `puf.csv` file), two of them had elderly heads with unspecified spouse age (that is, `age_spouse` == 1).  This meant that the age differences for those two units were 84 (head age 85 minus 1) and 72 (head age 73 minus 1).
```
$ awk -F, 'NR>1&&$11==2{d=$1-$2;n[d]++}
           END{for(d in n)print d,n[d]}' puf.csv | awk '{t+=$2}$1>=-9&&$1<=9{n+=$2}
                                                        END{print t,n,100*n/t}'
109175 89626 82.0939
```
The above tabulation shows that before these changes, only about 82 percent of the MARS==2 filing units had an age difference of nine years or less.

After the logic changes in the `age_consistency` function, we have the following results:
```
$ awk -F, 'NR>1&&$11==2{d=$1-$2;print $72,$1,d}' puf.csv | head
3455930 49 -7
3340520 49 -1
3649970 39 1
3234000 44 -3
3532720 37 -1
2977640 39 1
3623890 85 1
3623040 39 1
2898720 60 -1
3483490 73 6
```
and 
```
$ awk -F, 'NR>1&&$11==2{d=$1-$2;n[d]++}
           END{for(d in n)print d,n[d]}' puf.csv | awk '{t+=$2}$1>=-9&&$1<=9{n+=$2}
                                                        END{print t,n,100*n/t}'
109175 107267 98.2523
```
The above tabulation shows the 82 percent has risen to 98 percent.  Tabulations not shown here indicate that all the married filing units have an age difference of 19 years or less.

**Comment by martinholmer** [comment]
@andersonfrailey and @MattHJensen,  Could you review taxdata pull request #87?  Thanks.

**Comment by andersonfrailey** [comment]
@martinholmer, this looks good to me I just have one question. 
> age_spouse = np.where(age_sp < 16, 16, age_sp)

In the above line you set the minimum age for a spouse to be 16. What was the reasoning behind using 16 and not some other number? Is 16 the minimum age of a spouse found in the CPS?

**Comment by martinholmer** [comment]
@andersonfrailey asked:
>> age_spouse = np.where(age_sp < 16, 16, age_sp)
>
> In the above line you set the minimum age for a spouse to be 16. What was the reasoning behind using 16 and not some other number? Is 16 the minimum age of a spouse found in the CPS?

Good question.  The choice of 16 was arbitrary.  Your question got me wondering what are the lowest ages for head/spouse among married people in the `cps-matched-puf.csv` file.  So, here are the answers:
```
$ ~/work/OSPC/csvvars cps-matched-puf.csv | grep age
4 head_age
5 spouse_age
...
...
...
13 age_head
14 age_spouse
...
62 agerange

$ ~/work/OSPC/csvvars cps-matched-puf.csv | grep mars
82 mars
```
I don't understand why there are two sets of variables for a married couple's ages in the `cps-matched-puf.csv` file.  But as far as I can tell, they are identical.

Now let's look for young newly weds:
```
$ awk -F, 'NR>1&&$82==2{t++;n[$4]++}
           END{print t;for(a=2;a<20;a++)if(n[a]>0)print a,n[a]}' cps-matched-puf.csv 
109175
15 15
16 19
17 13
18 28
19 93

$ awk -F, 'NR>1&&$82==2{t++;n[$5]++}
           END{print t;for(a=2;a<20;a++)if(n[a]>0)print a,n[a]}' cps-matched-puf.csv 
109175
2 84
3 101
4 82
5 66
6 124
7 62
8 108
9 61
10 59
11 67
12 88
13 45
14 75
15 72
16 81
17 62
18 96
19 216

$ awk -F, 'NR>1&&$82==2{t++;n[$13]++}
           END{print t;for(a=2;a<20;a++)if(n[a]>0)print a,n[a]}' cps-matched-puf.csv 
109175
15 15
16 19
17 13
18 28
19 93

$ awk -F, 'NR>1&&$82==2{t++;n[$14]++}
           END{print t;for(a=2;a<20;a++)if(n[a]>0)print a,n[a]}' cps-matched-puf.csv 
109175
2 84
3 101
4 82
5 66
6 124
7 62
8 108
9 61
10 59
11 67
12 88
13 45
14 75
15 72
16 81
17 62
18 96
19 216
```
So, as you can see, the age of the youngest married head is 15, which seems not unreasonable.
But the age of the youngest spouse is 2, which is absurd.  These data imply there are hundreds of spouse who are under 10 years old.  I find the accuracy of these data highly suspect.

That is why I have imposed an arbitrary minimum spouse age in this pull request.  We can certainly discuss the most plausible minimum spouse age, but the need to impose some kind of minimum seem clear when you look at the data values.

Some years back, a statistician and I were using the PSID data to estimate a hazard (or waiting time) function for the age at first marriage.  In the PSID, which started data collection around 1968, there was a girl who got married at age 13.  All the related data for this person was consistent with marriage at a young age, so it seemed to us that the PSID data on this person was accurate.

Given what I have reported above, I'd be happy to change the 16 to 15, which would correspond to the age of the youngest married head.  Should I make that change?  I'm not very comfortable making the minimum less than 15 unless you can point me to some other relevant information.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @codykallen

**Comment by feenberg** [comment]
Do I see a 109 year old married to a 175 year old or do I not understand 
the tables?

dan

**Comment by Amy-Xu** [comment]
Dan, no one can deny the right of a 109-year-old getting married with someone older -- that is one basic human right :)

**Comment by martinholmer** [comment]
Following the suggestion made by @andersonfrailey, the minimum `age_spouse` value has been changed from the arbitrary value of 16 to a value of 15, which is smallest `age_head` value for those who are married in the `cps-matched-puf.csv` file.

**Comment by MattHJensen** [comment]
+1

This seems like a big improvement and can serve as a bandaid until the translation of the CPS-PUF matching scripts are complete and we can debug the issue at its source (which I presume is in the matching scripts.)

**Comment by martinholmer** [comment]
After changing the minimum `age_spouse` from 16 to 15, the `puf_data/finalprep.py` script produces a `puf.csv` file with slightly different ages for spouses.  Here are the current results:
```
$ csvvars puf.csv | grep age_
1 age_head
2 age_spouse
$ csvvars puf.csv | grep MARS
11 MARS

$ awk -F, 'NR>1&&$11==2{t++;n[$1]++}
           END{print t;for(a=2;a<20;a++)if(n[a]>0)print a,n[a]}' puf.csv 
109175  <--- unweighted count of all married heads
15 15
16 19
17 13
18 28
19 93
|  |
|  unweighted count of married heads of that age 
age of married head

$ awk -F, 'NR>1&&$11==2{t++;n[$2]++}
           END{print t;for(a=2;a<20;a++)if(n[a]>0)print a,n[a]}' puf.csv 
109175  <--- unweighted count of all married heads
15 123
16 62
17 102
18 141
19 181
|  |
|  unweighted count of married spouses of that age 
age of married spouse
```

**Comment by martinholmer** [comment]
The taxdata pull request #87 is going to be merged soon as a temporary fix for the unreasonable `age_spouse` values in the `cps-matched-puf.csv` file.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun

**Comment by andersonfrailey** [comment]
Thanks for the work on this, @martinholmer. Julia, our intern, discovered a bug in the original SAS code that caused the spouse to be misidentified when creating some of the CPS tax units, which could explain some of the major disparities in age we have been seeing.

She found a fix for it and I will work on evaluating the results before the next PUF release.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Julia, our intern, discovered a bug in the original SAS code that caused the spouse to be misidentified when creating some of the CPS tax units, which could explain some of the major disparities in age we have been seeing.
>
> She found a fix for it and I will work on evaluating the results before the next PUF release.

Great!  We will wait for that fix, which will hopefully make pull request #87 obsolete, before distributing the new version of the `puf.csv` file.

Just let me know when you have a new `cps-matched-puf.csv` file and I will be happy to undo the changes in #87.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @codykallen

**Pull request merged**
