### PR TITLE
Add under5

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR addresses issue #42. All I did was use the `agedp*` variables to count the number of children under 5 in each tax unit. 

It shows a change in the `remove_unused_variables` function because for some reason I couldn't merge my branch with master to include the line adding `p87482` to the unused variables list before pushing.

@MattHJensen

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey said about taxdata PR #43:
> All I did was use the agedp* variables to count the number of children under 5 in each tax unit.

So then, why is there this change in PR #43?
```
 -        'e11070', 'e11550', 'e11580', 'FDED',
 +        'e11070', 'e11550', 'e11580', 'p87482', 'FDED',
```
Adding `p87482` was done in taxdata PR #37.  Why are you doing it again?  Aren't you using the most recent version of the master branch?

@MattHJensen @Amy-Xu

**Comment by andersonfrailey** [comment]
@martinholmer 

> Adding p87482 was done in taxdata PR #37. Why are you doing it again? Aren't you using the most recent version of the master branch?

I did try and update my branch to the most recent version of the master branch, but for some reason the merge failed. I even tried cloning the repo again, but when I did that I couldn't push anything. 

I'm looking into what could have caused this but for times sake and because it was such a small difference I went ahead and pushed what I could.

**Comment by martinholmer** [comment]
@andersonfrailey,  Why can't we have a little consistency in variable naming?  Only a few days ago you added the `nu13` variable indicating the number of kids in the filing unit who are under 13 years of age.  So, now you want to introduce a new variable whose value is the number of kids in the filing unit who are under 5 years of age.  Why not call this new variable `nu5` or `nu05`?
I don't get your variable naming scheme.  Can you explain?

@MattHJensen @Amy-Xu

**Comment by andersonfrailey** [comment]
@martinholmer the `under5` name came about simply because it was the name used when we first talked about adding this variable. I've updated this PR to address your suggestions in latest commit. It shows more changes than I actually made because of another issue I was having with git. I believe I have everything worked out now so that shouldn't be a problem in the future.

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks so much for the quick response.

**Comment by martinholmer** [comment]
Why hasn't taxdata pull request #43 been merged into the master branch?

@andersonfrailey @MattHJensen @Amy-Xu

**Comment by Amy-Xu** [comment]
@andersonfrailey Is this a part of code for the current version of puf.csv?

**Comment by andersonfrailey** [comment]
@Amy-Xu yes, it is.

**Comment by martinholmer** [comment]
@Amy-Xu asked:
> Is [#43] part of code for the current version of puf.csv?

@andersonfrailey answered:
> yes, it is.

But then how come I don't see that code on the taxdata master branch?
And if "it is", how can it be that the `puf-2016-10-28.csv` file does not include the `n05` variable?
```
Mac2:final prep mrh$ ../../../csvvars puf-2016-10-28.csv | grep n
10 n24
72 cmbtp_standard
80 nu13
81 elderly_dependent
```

@MattHJensen

**Comment by Amy-Xu** [comment]
Anyways let's get this merged and make sure at least next version gets this imputation.

**Pull request merged**
