### PR TITLE
Updated script 1) remove extra variables 2) adjust variable names for 08 PUF

### PR DESCRIPTION
**Pull request by Amy-Xu**
@martinholmer Could you please review the script when you get a chance? Thanks

### CODE REVIEW

**Comment by martinholmer** [comment]
Amy,

This looks good, but I haven't been able to test the files it produces.
Did you want to handle the eight-thousand-some missing variables as part
of this pull request?

Best wishes, Martin

**Comment by Amy-Xu** [comment]
Earlier this week Matt told me there's going to be a updated 09 file, and theoretically there shouldn't be any missing values anymore. I'm thinking probably we can wait a bit on that part?

**Comment by martinholmer** [comment]
OK.  That sounds fine.

**Comment by Amy-Xu** [comment]
@martinholmer Feedback from SOI says those values simply should be zeros. I think it's also how we're dealing with them now, right?

**Comment by martinholmer** [comment]
No. They are BLANK, which is not the same as zero in Pandas.  So, could you make the missing values zero in the final prep script in the tax data repo?

**Comment by Amy-Xu** [comment]
@martinholmer Can I replace them manually? Somehow neither regex nor string could get the blanks replaced........

**Comment by martinholmer** [comment]
Amy,
I'm confused.  I thought you said that Matt told you that John O'Hare was going to fix this problem soon.

But if you want to fix this problem in the ```puf-cps-processing.py``` script, then won't something like this work (warning: I haven't tested this code fragment)?
```
df[df[varname]==np.nan] = 0.
```

Won't that assign zero for every NaN (missing value) for the dataframe column with ```varname```

cc @Amy-Xu @MattHJensen

**Comment by martinholmer** [comment]
@Amy-Xu,  Why don't you go ahead and merge taxdata pull request #13 into the taxdata master branch?

**Comment by Amy-Xu** [comment]
Thanks for reminding @martinholmer. 

Merging.

**Pull request merged**
