### PR TITLE
Move Age Variable Counts to SAS Scripts

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR moves the creation of `nu13`, `nu05`, `n24`, `elderly_dependent`, `f2441`, and `EIC` for the CPS file from `finalprep.py` to the SAS scripts. I'm doing this because final prep was only able to count up to five dependents for each of these variables, while in the SAS scripts we should be able to catch all of them.

It is labeled WIP because `n24` exceeds `nu18` in about 7% of the records still. I'll remove the label when I figure out why this is the case. I also incremented `EIC` incorrectly for 2013 and 2014, which I'll fix in my next commit.

### CODE REVIEW

**Comment by andersonfrailey** [comment]
I've added some checks in the SAS scripts to ensure that `n24` will not exceed `nu18` now. `n24` is now less than or equal to `nu18` in each record in the CPS.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> I've added some checks in the SAS scripts to ensure that `n24` will not exceed `nu18` now. `n24` is now less than or equal to `nu18` in each record in the CPS.

That's great!  Thanks for the quick resolution of this issue. 
Why don't you removed the WIP part of the title of PR #183 and merge it.

**Comment by martinholmer** [comment]
@andersonfrailey,  Do you think the changes in pull request #183 will resolve issue #149?

**Comment by andersonfrailey** [comment]
@martinholmer, the issue in #149 was resolved in PR #151 for the CPS file. I'm still working on a fix for the PUF. This PR was aimed at resolving just #157.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> The issue in #149 was resolved in PR #151 for the CPS file. I'm still working on a fix for the PUF. This PR #183 was aimed at resolving just #157.

OK.  Thanks for the clarification.

**Comment by andersonfrailey** [comment]
Updated this PR now that #184 has been merged. Ready to go upon review.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Updated this PR #183 now that #184 has been merged. Ready to go upon review.

I'm not conversant with SAS.  Are you going to ask @Amy-Xu to review #183?

**Comment by andersonfrailey** [comment]
@Amy-Xu can review the code and anyone should be able to download the individual CSV files to look through if they so choose.

**Comment by andersonfrailey** [comment]
If there are no additional comments I'll merge this at the end of the work day.

**Comment by Amy-Xu** [comment]
Sorry for the delay. Looks good to me.

**Pull request merged**
