### PR TITLE
Update PR 121 for minor bug fixes and completion of updates

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR updates PR #121 by @Jennydeng123 to fix a few minor bugs in her code. Information about these updates can be found in that PR's first comment. I've opened this PR rather than working off of @Jennydeng123's is so that we can get it reviewed and merged quickly now that the newest Republican tax plan has been released.

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Latest commits update the grow factors, weights, and stage 3 adjustment factors. Working on a notebook to compare our current PUF, weights, and growth factors to the ones produced in this PR.

**Comment by andersonfrailey** [comment]
[Here](http://nbviewer.jupyter.org/github/andersonfrailey/Notebook-Uploads/blob/master/2027%20Extrapolation%20Notebook.ipynb) is the first version of the notebook. I'll be adding 2027 projections for the new calculator in the morning, but everything up to that point looks pretty similar to our current PUF.

**Comment by MattHJensen** [comment]
cc @codykallen

**Comment by andersonfrailey** [comment]
I'm having trouble adding 2027 calculations to the notebook. Things get a little thrown off when you try to add a year to the extrapolation and compare with the current files.

When I make the needed updates to Tax-Calculator and run it with the new files. Working on updating all of the tests in tax-calculator then will open a corresponding PR.

**Comment by andersonfrailey** [comment]
Now that Tax-Calculator PR [#1624](https://github.com/open-source-economics/Tax-Calculator/pull/1624) has been merged, I will also be merging this PR. Thanks again @Jennydeng123 for getting this started!

**Pull request merged**
