### PR TITLE
Move taxdata to using only Python 3.6

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request changes the `environment.yml` specification of the `taxdata-dev` environment to require Python 3.6.5 or higher.  This means Python 2.7 can no longer by used to develop taxdata.  This change has been planned for many months.  Also, the `.travis.yml` file has been revised so that the GitHub tests use Python 3.6.

When using Python 3.6.5 and after touching all the `*py` files in the taxdata repository, I executed "make all".  The "make all" ran for five hours and produced the same CSV data files as on the master branch except for one: the `puf_data/puf.csv` file.  The unweighted sum of the `e19200` variable changed by one (increasing from 1951888779 to 1951888780), suggesting a float-to-integer rounding difference in one case as documented [here](https://github.com/open-source-economics/taxdata/pull/283#issuecomment-420293108).   Here is the information on the new and old (master branch) `puf.csv` files:
```
taxdata mrh$ ls -l puf_data/puf*csv
-rw-r--r--  1 mrh  staff  56415698 Sep  5 18:02 puf_data/puf-master.csv
-rw-r--r--  1 mrh  staff  56415698 Sep  9 17:43 puf_data/puf.csv
taxdata mrh$ md5 puf_data/puf*csv
MD5 (puf_data/puf-master.csv) = a10091a770472254c50f8985d8839162
MD5 (puf_data/puf.csv) = 3f1c7c2b16b6394a9148779db992bed1
```
Note that using this new `puf.csv` file (rather than the master-branch `puf.csv` file) on the `develop-with-python36` Tax-Calculator branch (that is, with the changes in [Tax-Calculator pull request 2058](https://github.com/open-source-economics/Tax-Calculator/pull/2058)) cause no additional changes in pytest results.

@andersonfrailey, can you generate this slightly different `puf.csv` file on your computer using the changes in this pull request?

### CODE REVIEW

**Comment by andersonfrailey** [comment]
@martinholmer I will run everything overnight and see if I get the slightly different PUF. I will report back in the morning.

**Comment by andersonfrailey** [comment]
@martinholmer after running all of the creation scripts with the new environment specs I produced a PUF with the same MD5 as you did.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> after running all of the creation scripts with the new environment specs [in PR #283] I produced a PUF with the same MD5 as you did.

@andersonfrailey, Thanks for double checking.   
Shall I merge #283 now?  
Do you think we need to issue a new `puf.csv` even though the Tax-Calculator test results are no different?  To be absolutely correct about this, I guess we should issue a new `puf.csv` file.  Is it too much work from your point of view?

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Issuing a new PUF isn't a lot of work, but Tax-Calculator users may be getting a little overwhelmed with the number of new PUFs we've issued in the past few weeks. If there are no PUF updates coming in the immediate future, lets go ahead and issue a new file just so that everyone is on the same page. If there are (I have no plans of making any, but you might) lets wait until we make those before issuing a new PUF.

I don't have any plans to change the `puf.csv` file contents.

**Comment by andersonfrailey** [comment]
@martinholmer ok. I'll send out a new PUF later today.

**Pull request merged**
