### PR TITLE
Add 5 million target to SOI Estimates

### PR DESCRIPTION
**Pull request by andersonfrailey**
The first step I've taken to update our PUF is adding a new wages and salaries target for those with AGI above $5 million. For documentation purposes, here are the steps I took:
1. Split the wage_12 value in the SOI estimates into wage_12 and wage_13. Wage_12 is now the wages of those with AGI between $1 million and $5 million and wage_13 is for those with AGI above $5 million.
2. Modified Stage_I.py, Single_Year_Stage_II.py, and CLP_solver_16Years.py to account for this extra target.
3. Changed the base year in Stage_I.py to 2009. This changed the SOI targets and Stage I factors used in Stage II.
4. Added a filter that was previously missing to ss_income in order to accurately target this value and make the linear programming model solvable. 
5. Generate new weights for the PUF based on these changed

[These](https://github.com/open-source-economics/taxdata/files/545233/5mTargets.xlsx) are the resulting changes in TaxCalc output and the differences between the new and old weights.

My only concern are rather large changes in some of the targets for later years, namely taxable interest income, dividends, and unemployment compensation. I'm currently looking into what may have caused this and will post any significant findings.

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Here is a breakdown of the percent of total AGI by size of AGI in 2014:

| AGI            | New PUF | Current PUF | IRS     | 
|----------------|---------|-------------|---------| 
| Less than $0    | -1.566% | -1.331%     | -2.023% | 
| $1 - $10k      | 1.351%  | 1.473%      | 1.188%  | 
| $10k - $20k    | 3.476%  | 3.646%      | 3.598%  | 
| $20k - $30k    | 4.437%  | 4.506%      | 4.788%  | 
| $30k - $40k    | 4.757%  | 4.804%      | 5.194%  | 
| $40k - $50k    | 4.893%  | 4.939%      | 5.260%  | 
| $50k - $75k    | 12.280% | 12.312%     | 12.199% | 
| $75k - $100k   | 10.621% | 10.662%     | 11.377% | 
| $100k - $200k  | 23.593% | 24.428%     | 24.171% | 
| $200k - $500k  | 13.945% | 15.275%     | 14.530% | 
| $500k - $1m    | 5.648%  | 5.921%      | 5.758%  | 
| $1m - $5m        | 7.705%  | 7.597%      | 6.923%  | 
| Above $5m      | 8.859%  | 5.769%      | 7.037%  |

**Comment by MattHJensen** [comment]
@andersonfrailey, this is interesting. Getting the wage and salary distribution right at the high end means that we go pretty far over on AGI. Do you think this is because we aren't targeting the distribution for other income types, and too much of that income is showing up at the very top?

**Comment by andersonfrailey** [comment]
@MattHJensen, it's possible that's an issue. Looking at a few other sources of income, the distribution found in the IRS data can vary quite a bit:

| AGI            | WAS     | Taxable Interest | Ordinary Dividends | Business Income | Taxable Capital Gains | 
|----------------|---------|------------------|--------------------|-----------------|-----------------------| 
| Less than 0    | 0.286%  | 4.942%           | 1.850%             | 1.085%          | 2.214%                | 
| $1 - $10k      | 1.399%  | 1.383%           | 0.959%             | 4.607%          | 0.322%                | 
| $10k - $20k    | 3.861%  | 2.267%           | 1.443%             | 11.165%         | 0.420%                | 
| $20k - $30k    | 5.619%  | 3.623%           | 1.539%             | 6.629%          | 0.503%                | 
| $30k - $40k    | 6.169%  | 2.210%           | 1.616%             | 5.316%          | 0.500%                | 
| $40k - $50k    | 6.166%  | 2.003%           | 1.835%             | 4.335%          | 0.651%                | 
| $50k - $75k    | 13.510% | 6.278%           | 5.649%             | 8.969%          | 2.051%                | 
| $75k - $100k   | 12.389% | 5.284%           | 5.630%             | 7.865%          | 2.418%                | 
| $100k - $200k  | 25.930% | 14.115%          | 16.936%            | 19.529%         | 8.108%                | 
| $200k - $500k  | 14.080% | 13.415%          | 17.484%            | 17.173%         | 12.420%               | 
| $500k - $1m    | 4.574%  | 7.183%           | 9.647%             | 6.496%          | 9.084%                | 
| 1m - 5m        | 3.965%  | 14.238%          | 14.596%            | 5.049%          | 18.819%               | 
| Above $5m      | 2.052%  | 23.059%          | 20.817%            | 1.783%          | 42.489%               | 

@Amy-Xu would probably have a more in depth answer, but I think not targeting other income sources could be an issue.

**Comment by MattHJensen** [comment]
Thanks @andersonfrailey. I'm interested to hear what you and @amy-xu think about adding distributional targets for the other core income measures. Is it something we should try and see how it goes? Are there downsides we wouldn't observe in the resulting file? Is it a time consuming project?

**Comment by andersonfrailey** [comment]
Update: Because adding the $5 million target causes AGI to move further from actual totals than what the current `puf.csv` and 'WEIGHTS.csv` currently give us, this new puf will not be distributed until this problem is resolved. 

In the meantime, a new `puf.csv` file with these three changes will be distributed:

1. Add a variable indicated an elderly dependent, `elderly_dependent`
2. Add a variable with the number of dependents under 13 in the tax unit,` nu13`
3. Remove `p87482` to take care of PR #37 

@Amy-Xu @MattHJensen @martinholmer @talumbau @GoFroggyRun

**Comment by martinholmer** [comment]
@andersonfrailey, What is the status of PR #40 ? Has it been superceeded by other more recent pull requests? If so, please close (without merging) PR #40. If not, please explain how #40 fits in with the other pending pull requests.

**Comment by andersonfrailey** [comment]
@martinholmer we attempted to implement PR #40 but the results were not what we were hoping for so this idea was shelved. Closing.

**Pull request closed without merging**
