### PR TITLE
Updates for Benefit files

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR does a few things.

First, it fixes an issue with the column labels of the SSI and OASDI benefits in the raw cps file. @hdoupe and I noticed that the columns were labeled `ss_ben` and `ssi_ben` rather than `SS` and `SSI` as we were expecting in `finalprep.py`. We traced this back to PR #120 and the early work done writing the benefit extrapolation scripts. A script was written to rename the benefit relate variables to work with the extrapolation script, and this script overwrote `cps_raw.csv.gz` with these new names and I then merged it in. In the final version of the extrapolation script, the `cps_raw.csv.gz` file with the renamed columns is written to a new file to avoid this issue. I want  to emphasis that this had no impact on the actual values of the data or any Tax-Calculator runs that used the CPS file. It was only an issue with these column names.

This bug was caught because `finalprep.py` was not fully updated to reflect the new names in PR #120. As can be seen in the "files changed" section of the PR, `VB`, `MEDICARE`, and `MEDICAID` were replaced by `vb_ben`, `medicare_ben`, and `medicaid_ben` during the rename variables section of `finalprep.py`. The latter names were the result of the file overwriting, not the SAS scripts. Using the new names was a mistake on my end and I'll fix it in an additional commit on this PR.

Second, it adds the `benefitprograms.csv` file that contains information for all of the non-modeled benefit programs.

Third, it makes a few changes to complete the switch from using `ss_ben` and to using `oasdi_ben`.

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey,  does this "drop 2014 benefits, change names" mean you are dropping 2014 benefit from the `cps.csv.gz` file?  If so, excellent.  If it means you dropped 2014 benefits from the `cps_benefits.csv.gz` file, you should reconsider you strategy.  See my comments in Tax-Calculator pull request 1719.

**Comment by martinholmer** [comment]
@andersonfrailey,  I have a few questions about taxdata pull request #146:

1. The ` cps_data/benefitprograms.csv` is now more informative, but can you point us to where the `other_ben` amounts are constructed and placed into the new `cps.csv.gz` file?  I'm wondering about that because your latest commit removes a few other benefits from the documentation file, but I don't see any code changes that actually drops them out of the data file.

2. Why is `Unemployment Assistance,11.3,16,43504` in `other_ben`.  I thought we discussed this in Tax-Calculator PR1719.  Tax-Calculator already has unemployment benefits, so isn't adding them here in `other_ben` double counting them?

3. Why is `Veterans non-service connected pensions,11.3,49,5251` in `other_ben`?  You already have `vet_ben` in `cps.csv.gz` for 2014 and in `cps_benefits.csv.gz` for 2015+.  And in PR1719 that variable is described this way:
```
"vet_ben": {
      "type": "float",
      "desc": "Imputed Veteran's benefits",
      "form": {"2014-2027": "imputed using the C-TAM model"},
      "availability": "taxdata_cps"
```
To me, this description implies that **all** veteran's benefits are included.  They is no qualification that says it includes only some veteran's benefits.  So, that's why the item `Veterans non-service connected pensions` included in `other_ben` is worrisome.  What's going on here?

**Comment by andersonfrailey** [comment]
>The cps_data/benefitprograms.csv is now more informative, but can you point us to where the other_ben amounts are constructed and placed into the new cps.csv.gz file? I'm wondering about that because your latest commit removes a few other benefits from the documentation file, but I don't see any code changes that actually drops them out of the data file.

We originally just copy/pasted the values form the specified documents, rather than parse the spreadsheet with code. I simply deleted the rows of variables we are no longer using to update this PR.

>Why is Unemployment Assistance,11.3,16,43504 in other_ben. I thought we discussed this in Tax-Calculator PR1719. Tax-Calculator already has unemployment benefits, so isn't adding them here in other_ben double counting them?

I mentioned in my [last comment](https://github.com/open-source-economics/Tax-Calculator/pull/1719#issuecomment-359084066) in that I wasn't positive Unemployment Assistance and the unemployment compensation are referencing the same thing. Unemployment Assistance listed in `benefitprograms.csv` is about $9 billion more than what is listed in the PUF and about $16 billion more than the CPS (I only mentioned the PUF numbers in my Tax-Calculator comment).

>To me, this description implies that all veteran's benefits are included. They is no qualification that says it includes only some veteran's benefits. So, that's why the item Veterans non-service connected pensions included in other_ben is worrisome. What's going on here?

I believe you're correct here and that should be removed. @Amy-Xu can you confirm that the imputed veteran's benefits include all benefits?

**Comment by martinholmer** [comment]
@andersonfrailey said:
> We originally just copy/pasted the values form the specified documents, rather than parse the spreadsheet with code. I simply deleted the rows of variables we are no longer using to update this PR.

Where in the taxdata code are the individual other benefits added together and distributed among filing units?

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>Where in the taxdata code are the individual other benefits added together and distributed among filing units?

In [this function](https://github.com/open-source-economics/taxdata/blob/bc147d2bc9de11b88e51c18ae35ae24edbd87a2f/cps_data/finalprep.py#L359) in `finalprep.py`

**Comment by andersonfrailey** [comment]
I just noticed a bug in that function. When calculating the total of the benefits used to distribute the other benefits, I added the weights rather than multiplying them. I also need to multiply the costs by 1e6 because they're listed in millions.

**Comment by martinholmer** [comment]
@andersonfrailey has latest calculation of `other_ben` this way:
```
def benefits(data, other_ben):
    """
    Distribute benefits from non-modeled benefit programs and create 
    other benefits variable
    """
    # Distribute other benefits
    data['dist_ben'] = (data['mcaid_ben'] + data['ssi_ben'] +
                        data['snap_ben'] + data['vet_ben'])
    data['ratio'] = (data['dist_ben'] * data['s006'] /
                     (data['dist_ben'] * data['s006']).sum())
    other_ben['2014_cost'] *= 1e6
    data['other_ben'] = (data['ratio'] * other_ben['2014_cost'].sum() /
                         data['s006'])
```
I'm a little slow on these dataframe programming techniques, so bear with me.

I understand the first three of the above four statements:
1. compute a distribution benefit for each funit
2. compute a ratio (of the distribution benefit) for each funit
3. scale up the 2014 cost of each other benefit to dollars

But how would I say what is going on in the fourth statement?

I don't see where all the individual other benefits are added together to get the total other benefit.

And I don't see why you're dividing by the weight.

I'm probably confused, but would like some guidance in understanding what's going on in this code.

If the forty-some other benefit amounts are added together for each funit somewhere else, where is that done in the code?  And even if that is done somewhere else in the code, why does the fourth statement divide by the funit weight.

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>I don't see where all the individual other benefits are added together to get the total other benefit.

They're added together with this piece of the code:
```python
other_ben['2014_cost'].sum()
```
using `.sum()` is an easy way to add together all of the elements in a column of a DataFrame.

Ultimately, `data['ratio'] * other_ben['2014_cost'].sum()` distributes the sum of the benefits across tax units and that is divided the that by the weight for each unit.

I divided by the weight because when working in Tax-Calculator you find the aggregate total of a variable by taking the sum of the variable multiplied by the weight. Here, we're effectively distributing a weighted sum across the tax units. In my opinion, rather than expecting user to consistently remember that `other_ben` is the one variable you shouldn't multiply by `s006` to find the true total, simply dividing the portion of `other_ben` distribute to each tax unit by their weight here would be a better way to avoid an over calculation of these other benefits when working with Tax-Calculator.

**Comment by martinholmer** [comment]
@andersonfrailey answered my question:
>> I don't see where all the individual other benefits are added together to get the total other benefit.
>
>They're added together with this piece of the code:
>```python
>other_ben['2014_cost'].sum()
>```
>using `.sum()` is an easy way to add together all of the elements in a column of a DataFrame.
>
>Ultimately, `data['ratio'] * other_ben['2014_cost'].sum()` distributes the sum of the benefits across tax units and that is divided the that by the weight for each unit.
>
>I divided by the weight because when working in Tax-Calculator you find the aggregate total of a variable by taking the sum of the variable multiplied by the weight. Here, we're effectively distributing a weighted sum across the tax units. In my opinion, rather than expecting user to consistently remember that `other_ben` is the one variable you shouldn't multiply by `s006` to find the true total, simply dividing the portion of `other_ben` distribute to each tax unit by their weight here would be a better way to avoid an over calculation of these other benefits  when working with Tax-Calculator.

Thanks for being patient with my novice Pandas skills.  Your explanation makes perfect sense.  I guess my confusion was rooted in not being aware of the index of `other_ben`.  And you're absolutely correct in dividing by each funit's sample weight.

Now we just need agreement on which lines should be included in the `benefitprograms.csv` file.

**Comment by andersonfrailey** [comment]
Part of the discrepancy between  "Unemployment Assistance" in `benefitprograms.csv` and unemployment compensation in the CPS is likely due to what the CPS is counting as unemployment compensation. Looking through the [CPS documentation](http://nber.org/cps/cpsmar2014.pdf), unemployment compensation includes income from government agencies, unions, and private companies. So it makes sense that `e02300` is higher than unemployment assistance. There is one variable, `STRKUC`, that indicates whether a person received unemployment/strike benefits from a union, but the actual amounts are never broken down by source.

I think it would be reasonable to assume the federal unemployment benefits found in unemployment assistance are include in the CPS measures of unemployment compensation, but I don't believe we will be able to distinguish between what comes from the government and what is from unions/private sources using just the CPS.

As for "Veterans non-service connected pensions", these are benefits for [wartime veterans who have limited or no income and who are at least 65 or, if under 65, are permanently and totally disabled](http://www.vetangels.org/frequently-asked-questions/). The CPS has variables to indicate age, disability status, and whether or not a person receives veterans benefits. Veterans benefits are further broken down into the type of veterans payments received: service-connected disability compensation, survivor benefits, veterans' pension, education assistance, other.

For each CPS file that goes into `CPS.csv`, I looked at how many receive veterans benefits, and then within that group how many are over 65, receiving a veterans pension but not service related disability compensation, and are disabled; and those under 65 meeting the same criteria. These are the unweighted totals I got:
```
2013 CPS
	Total Records Receiving Veterans Benefits: 1957
	Over 65: 768
		Receiving a pension, but not service related disability comp: 226
		Receiving a pension, but not service related disability comp and disabled: 96

	Under 65: 1189
		Receiving a pension, but not service related disability comp: 158
		Receiving a pension, but not service related disability comp and disabled: 38

2014 CPS
	Total Records Receiving Veterans Benefits: 1430
	Over 65: 625
		Receiving a pension, but not service related disability comp: 137
		Receiving a pension, but not service related disability comp and disabled: 48

	Under 65: 805
		Receiving a pension, but not service related disability comp: 120
		Receiving a pension, but not service related disability comp and disabled: 19

2015 CPS
	Total Records Receiving Veterans Benefits: 2225
	Over 65: 1001
		Receiving a pension, but not service related disability comp: 221
		Receiving a pension, but not service related disability comp and disabled: 97

	Under 65: 1224
		Receiving a pension, but not service related disability comp: 152
		Receiving a pension, but not service related disability comp and disabled: 27
```

It looks like there are some records in each file who are disabled and receive veterans pensions but not service-connected disability benefits, which could indicate they're receiving these non-service connected pensions. I'm not sure what more could be done to be certain about that though.

cc @martinholmer @MattHJensen @Amy-Xu

**Comment by andersonfrailey** [comment]
And while we're on the topic of what benefits to include where, how do y'all feel about using `oasdi_ben` as `e02400` in `CPS.csv`? We just wouldn't include `oasdi_ben` in the final file and in the section where you remove benefits the user would be zeroing out `e02400`. The thought process here is, we're using C-TAM to impute these benefits because we believe the output is better than what is in the CPS so we should replace the CPS values with the more accurate C-TAM output.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> And while we're on the topic of what benefits to include where, how do y'all feel about using `oasdi_ben` as `e02400` in the `cps.csv` file?   We just wouldn't include `oasdi_ben` in the final file and in the section where you remove [that is, repeal] benefits the user would be zeroing out `e02400`.  The thought process here is, we're using C-TAM to impute these benefits because we believe the output is better than what is in the CPS so we should replace the CPS values [of `e02400`] with the more accurate C-TAM [`oasdi_ben` variable].

This makes perfect sense.   The new `cps.csv` file would contain 2014 values that are the same as the 2014 values of the C-TAM `oasdi_ben` variable, and then the `oasdi_ben` variable can be dropped from both the new`cps.csv` file and from the new `cps_benefits.csv` file.

The only remaining question is this:
How are we going to extrapolate `e02400` values to 2015 and subsequent years?

One possibility is this approach:

- Revise the `_ASOCSEC` growfactor values, which are used only for extrapolating `e02400` amounts, so that the new 2014 `e02400` values extrapolate to the C-TAM target aggregates for OASDI benefits in 2015+.

Or maybe there is a better approach.

@MattHJensen @Amy-Xu @feenberg @hdoupe

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Part of the discrepancy between "Unemployment Assistance" in `benefitprograms.csv` and unemployment compensation in the CPS [`e02300`] is likely due to what the CPS is counting as unemployment compensation. Looking through the CPS documentation, unemployment compensation includes income from government agencies, unions, and private companies. So it makes sense that `e02300` is higher than unemployment assistance [which is $43.504 billion in 2014 in `benefitprograms.csv`]. There is one variable, STRKUC, that indicates whether a person received unemployment/strike benefits from a union, but the actual amounts are never broken down by source.
>
> I think it would be reasonable to assume the federal unemployment benefits found in unemployment assistance are include in the CPS measures of unemployment compensation, but I don't believe we will be able to distinguish between what comes from the government and what is from unions/private sources using just the CPS.

What is the weighted 2014 total of `e02300` in the `cps.csv` file?  

If we want `e02300` to include only government unemployment insurance (which makes sense to me), you could simply scale down each positive `e02300` value in `cps.csv` by multiplicative factor that produces a 2014 weighted `e02300` total equal to $43.504 billion.  Then drop the "Unemployment Assistance" row in `benefitprograms.csv` file (because we have government unemployment benefits in the `e02300` variable).  And then in Tax-Calculator pull request 1719, add a new policy variable called `ui_repeal` (or some other similar name) that zeros out `e02300` when true.

**Comment by martinholmer** [comment]
@andersonfrailey,  One more question about the contents of the `benefitprograms.csv` file.
Here is one of the rows:
```
Payment where child credit exceeds tax liability,11.3,51,21490
```
Over $21 billion in refundable CTC payments, right?

If that's what this row is referring to, then shouldn't it be removed from the `benefitprograms.csv` file?
Tax-Calculator already computes this amount as part of its income tax calculations.  You recently removed the EITC row in the the `benefitprograms.csv` file because the EITC was being calculated by Tax-Calculator.  Wouldn't the same logic apply in this case?

@MattHJensen @Amy-Xu

**Comment by andersonfrailey** [comment]
@martinholmer  asked:
>What is the weighted 2014 total of e02300 in the cps.csv file?

27,086,366,177.51. About 62% of what is reported in Unemployment Assistance in `benefitprograms.csv`, which goes against my theory that we would expect higher unemployment compensation in the CPS file. IRS [stats](https://www.irs.gov/statistics/soi-tax-stats-individual-statistical-tables-by-size-of-adjusted-gross-income) show about $33 billion in unemployment compensation for the year. It's possible that maybe they are different things, or there's systematic under-reporting of unemployment compensation in the CPS.

>Tax-Calculator already computes this amount as part of its income tax calculations.

Is this the refundable portion of the child tax credit (c11070)? If so then yes, based on some googling, it appears that c11070 is the same as `Payments where child credit exceeds tax liability`. When I look I checked the total in Tax-Calculator and there is a roughly $2 billion dollar difference between `Payments where child credit exceeds tax liability` and `c11070` when using the CPS file.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> As for "Veterans non-service connected pensions", these are benefits for wartime veterans who have limited or no income and who are at least 65 or, if under 65, are permanently and totally disabled. The CPS has variables to indicate age, disability status, and whether or not a person receives veterans benefits. Veterans benefits are further broken down into the type of veterans payments received: service-connected disability compensation, survivor benefits, **veterans' pension**, education assistance, other.

So, are you saying that the CPS has no information on "non-service connected pensions"?

Aren't those included in **veterans' pensions**?

**Comment by martinholmer** [comment]
@andersonfrailey said:
>> What is the weighted 2014 total of e02300 in the `cps.csv` file?

27,086,366,177.51.   About 62% of what is reported in Unemployment Assistance in `benefitprograms.csv`, which goes against my theory that we would expect higher unemployment compensation in the CPS file. IRS stats show about $33 billion in unemployment compensation for the year. It's possible that maybe they are different things, or there's systematic under-reporting of unemployment compensation in the CPS.

Not likely to be "different things", much more likely that " there's systematic under-reporting of unemployment compensation in the CPS".  Researchers have know for decades that most benefits are under-reported by CPS respondents.

So, I still recommend my earlier suggestion, but now we know the multiplicative scaling factor is going to be greater than one (not less than one):

> If we want `e02300` to include only government unemployment insurance (which makes sense to me), you could simply scale up each positive `e02300` value in `cps.csv` by a multiplicative factor that produces a 2014 weighted `e02300` total equal to $43.504 billion. Then drop the "Unemployment Assistance" row in `benefitprograms.csv` file (because we have government unemployment benefits in the `e02300` variable). And then in Tax-Calculator pull request 1719, add a new policy variable called `_BEN_ui_repeal` that zeros out `e02300` when true.

**Comment by martinholmer** [comment]
@andersonfrailey said:
>> Tax-Calculator already computes this amount as part of its income tax calculations.
>
> Is this the refundable portion of the child tax credit (`c11070`)? If so then yes, based on some googling, it appears that `c11070` is the same as Payments where child credit exceeds tax liability. When I look I checked the total in Tax-Calculator and there is a roughly $2 billion dollar difference between Payments where child credit exceeds tax liability and `c11070` when using the CPS file.

That's close enough for "government work".  So, we'll drop that row from the `benefitprograms.csv` file, right?

**Comment by Amy-Xu** [comment]
Anderson asked:

>I believe you're correct here and that should be removed. @Amy-Xu can you confirm that the imputed veteran's benefits include all benefits?

Sorry this slipped through my hands. Our [imputation targets](https://www.va.gov/vetdata/Expenditures.asp) do have pensions included. But I'm not sure from the description of those benefits expenditure whether there is a further segmentation between 'service-related and 'non-service related' pension. I would assume pension is just pension, but could be mistaken.

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>So, are you saying that the CPS has no information on "non-service connected pensions"?
Aren't those included in veterans' pensions?

I'm assuming so, there is just nothing that explicitly states that in the documentation.

>So, I still recommend my earlier suggestion, but now we know the multiplicative scaling factor is going to be greater than one (not less than one):

I'm on board with this. And then in Tax-Calculator we will zero out `e02300` when the user removed unemployment benefits.

>That's close enough for "government work". So, we'll drop that row from the benefitprograms.csv file, right?

Right. I'll do that in the next commit.

@Amy-Xu said:
> I would assume pension is just pension, but could be mistaken.

I'm inclined to think that they include service and non-service connected pensions when reporting totals and the distinction between the two is only relevant when applying for pensions.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> I would assume pension is just pension, but could be mistaken.

Then @andersonfrailey said:
> I'm inclined to think that they include service and non-service connected pensions when reporting totals and the distinction between the two is only relevant when applying for pensions.

Does this mean the plan is to drop the veterans benefit row from the `benefitprograms.csv` file?

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>Does this mean the plan is to drop the veterans benefit row from the benefitprograms.csv file?

Yes.

Given our discussion in the past few comments, this is what I'm planning on doing:

1. Remove `payment where child credit exceeds tax liability` and `Veterans non-service connected pensions` from `benefitprograms.csv`
2. Leave `Unemployment Assistance` in `benefitprograms.csv` so that it can be used to determine the multiplicative factor @martinholmer suggested, but remove it from the DataFrame before the total `other_ben` is calculated and distributed among the tax units.


To address the need for growth factors for `other_ben` in Tax-Calculator, I want to use the projected and reported cost of these programs that are found in the same [documents](https://obamawhitehouse.archives.gov/omb/budget/Historicals) we're pulling 2014 costs from. These documents include totals and projections out to 2021. I'll use those to determine growth rates for 2015-2021 and assume it stays at 2021 levels out until 2027. These will be calculated in `stage1.py` and ultimately added to `growfactors.csv`.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Given our discussion in the past few comments, this is what I'm planning on doing:
>
>1. Remove `payment where child credit exceeds tax liability` and `Veterans non-service connected pensions` from `benefitprograms.csv`
>2. Leave `Unemployment Assistance` in `benefitprograms.csv` so that it can be used to determine the multiplicative factor @martinholmer suggested, but remove it from the DataFrame before the total `other_ben` is calculated and distributed among the tax units.
>
>To address the need for growth factors for `other_ben` in Tax-Calculator, I want to use the projected and reported cost of these programs that are found in the same [documents](https://obamawhitehouse.archives.gov/omb/budget/Historicals) we're pulling 2014 costs from. These documents include totals and projections out to 2021. I'll use those to determine growth rates for 2015-2021 and assume it stays at 2021 levels out until 2027. These will be calculated in `stage1.py` and ultimately added to `growfactors.csv`. 

Consulting the OMB other-benefits total for 2015-2021 is a good idea.  But what if the other-benefits growth factors are roughly the same as inflation (or some other existing growfactor)?  In that case, wouldn't it be easier to extrapolate the `other_ben` variable using an existing growfactor?  Adding a new one that has just this one use seems like a lot of extra work.

No matter which approach you adopt for the 2015-2021 `other_ben` extrapolation, it seems as if assuming a **zero** rate of growth in `other_ben` in the years after 2021 is a little extreme.  Why not continue the extrapolation of `other_ben` at the 2021 rate of growth (or an average of the growth rates for the last known few years)?

And are you going to scale the 2014 `cps.csv` values for `e02400` (social security benefits) so they sum up to the 2014 total for `oasdi_ben` in the C-TAM data?

When you write the new values for `e02300` and `e02400` in the revised `cps.csv` file, don't forget to write them as integers.

**Comment by andersonfrailey** [comment]
> In that case, wouldn't it be easier to extrapolate the other_ben variable using an existing growfactor? Adding a new one that has just this one use seems like a lot of extra work.

This is a good point. I'll take a look at how the growth rates OMB projected compares to what we have.

>No matter which approach you adopt for the 2015-2021 other_ben extrapolation, it seems as if assuming a zero rate of growth in other_ben in the years after 2021 is a little extreme. Why not continue the extrapolation of other_ben at the 2021 rate of growth (or an average of the growth rates for the last known few years)?

Sorry, should've been more clear. If we ultimately went this route, I would be continuing at the 2021 rate of growth, not assuming growth is zero.

>And are you going to scale the 2014 cps.csv values for e02400 (social security benefits) so they sum up to the 2014 total for oasdi_ben in the C-TAM data?

I'm not sure I understand this question. I thought we wanted to just replace `e02400` with `oasdi_ben` (`oasdi_ben` would become `e02400` and we drop what is currently used as `e02400`). So what scaling would need to be done?

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Sorry, should've been more clear. If we ultimately went this route, I would be continuing at the 2021 rate of growth, not assuming growth is zero.
>
>> And are you going to scale the 2014 `cps.csv` values for` e02400` (social security benefits) so they sum up to the 2014 total for `oasdi_ben` in the C-TAM data?
>
> I'm not sure I understand this question. I thought we wanted to just replace e02400 with oasdi_ben (oasdi_ben would become e02400 and we drop what is currently used as e02400). So what scaling would need to be done?

OK.  Sorry about my confusion on the post-2021 plan for `other_ben` extrapolation.

With respect to social security benefits, you plan to replace in the `cps.csv` file what we have now for `e02400` with the 2014 values of `oasdi_ben` and then drop the `oasdi_ben` variable from both the `cps.csv` and `cps_benfits.csv` files, right?  If my understanding of your plan is correct, then I'm happy with it.

**Comment by andersonfrailey** [comment]
>With respect to social security benefits, you plan to replace in the cps.csv file what we have now for e02400 with the 2014 values of oasdi_ben and then drop the oasdi_ben variable from both the cps.csv and cps_benfits.csv files, right? If my understanding of your plan is correct, then I'm happy with it.

This is correct. `oasdi_ben` will no longer be in `CPS.csv` or `cps_benefits.csv`. It will be used as the values for `e02400` and when repealing Social Security benefits in Tax-Calculator we will zero out `e02400`.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> This is correct. `oasdi_ben` will no longer be in `CPS.csv` or `cps_benefits.csv`. It will be used as the values for `e02400` and when repealing Social Security benefits in Tax-Calculator we will zero out `e02400`.

Sounds great!   Thanks for all the work on benefits data we're adding to Tax-Calculator.

**Comment by andersonfrailey** [comment]
Took a look at the growth rate of benefits from 2015-2021 and they are very small:

Year | Rate
-- | --
2015 | 1.0525
2016 | 1.0958
2017 | 1.0212
2018 | 1.0934
2019 | 1.0552
2020 | 1.0032
2021 | 1.0344

This doesn't line up too well with any single growth factor that we already have right now.

**Comment by andersonfrailey** [comment]
I've been playing around with using some of our existing growth factors for `other_ben` to see how the results look. As I mentioned in my previous comment, we don't have a growth rate that lines up well with what we see from the projections. I tried out using `ATXPY` and `AWAGE` as the growth rates and these are the totals (in billions) I got:

Year | Projections | ATXPY | AWAGE | ATXPY % Difference | AWAGE % Difference
-- | -- | -- | -- | -- | --
2015 | 302.82 | 300.27 | 299.81 | -0.84% | -0.99%
2016 | 331.84 | 312.66 | 314.25 | -5.78% | -5.30%
2017 | 338.89 | 327.61 | 330.5 | -3.33% | -2.48%
2018 | 370.54 | 344.42 | 347.04 | -7.05% | -6.34%
2019 | 391.00 | 361.48 | 362.32 | -7.55% | -7.34%
2020 | 392.25 | 378.87 | 377.08 | -3.41% | -3.87%
2021 | 405.74 | 397.75 | 393.03 | -1.97% | -3.13%
2022 | 419.69 | 417.56 | 410.56 | -0.51% | -2.18%
2023 | 434.12 | 438.15 | 429.2 | 0.93% | -1.13%
2024 | 449.05 | 459.77 | 448.78 | 2.39% | -0.06%
2025 | 464.49 | 482.1 | 469.32 | 3.79% | 1.04%
2026 | 480.46 | 506.26 | 490.91 | 5.37% | 2.17%
2027 | 496.99 | 531.44 | 513.58 | 6.93% | 3.34%

The projections represent the totals from the OMB until 2021. For 2022-2027 I used the growth rate seen between 2020 and 2021.

The results obviously aren't perfect, but there are some decent years. I'd love to hear some other thoughts on these or let me know if there are other growth factors you'd like me to try.

cc @martinholmer @MattHJensen @Amy-Xu

**Comment by andersonfrailey** [comment]
@martinholmer, can you expand a little on this comment about creating a new growth factor to go with `other_ben`:
>Consulting the OMB other-benefits total for 2015-2021 is a good idea. But what if the other-benefits growth factors are roughly the same as inflation (or some other existing growfactor)? In that case, wouldn't it be easier to extrapolate the `other_ben` variable using an existing growfactor? Adding a new one that has just this one use seems like a lot of extra work.

Was your point that we should only create a new factor if the growth factors for `other_ben` isn't close to one of the existing factors? If so, I think that the growth factors for `other_ben` are different enough that it would be worth creating a new factor.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Was your point that we should only create a new factor if the growth factors for other_ben isn't close to one of the existing factors? If so, I think that the growth factors for other_ben are different enough that it would be worth creating a new factor.

Fine.

**Comment by martinholmer** [comment]
@andersonfrailey,  Can PR#146 rename `n1821` to `n1820` in the `cps.csv.gz` file per issue #129?
PR#146 is all about preparing Tax-Calculator data for UBI/benefits policy analysis, so why not fix this long-standing bug as part of PR#146?  (The new `puf.csv` file that you're preparing can include the renamed `n1820` variable and then issue #129 will be fully resolved.)

**Comment by andersonfrailey** [comment]
> Can PR#146 rename n1821 to n1820 in the cps.csv.gz file per issue #129?

Absolutely

**Comment by andersonfrailey** [comment]
@martinholmer, my last commit changes the name of `n1821` to `n1820` to resolve #129. The CPS file in this PR is ready to go. I'll be adding the growth factor for `other_ben` shortly.

**Comment by andersonfrailey** [comment]
Latest commit updates stage 1 to include a new growth factor to be used with `other_ben`

**Comment by martinholmer** [comment]
@andersonfrailey, when I compare tabulations of the new (PR#146) `cps.csv.gz` file with the old file, I get the following  OASDI and UI results.

Tabulating the **OLD** file produces this:
```
$ python tab-cps-oasdi-ui.py
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
total OASDI benefits ($B): 688.592
total    UI benefits ($B):  27.086
total OASDI beneficiaries (M) 39.032
total    UI beneficiaries (M)  6.475
$ 
```

Tabulating the **NEW** file produces this:
```
$ python tab-cps-oasdi-ui.py
You loaded data for 2014.
Your data include the following unused variables that will be ignored:
  snap_ben
  mcare_ben
  other_ben
  ssi_ben
  mcaid_ben
  vet_ben
Tax-Calculator startup automatically extrapolated your data to 2014.
total OASDI benefits ($B): 853.241
total    UI benefits ($B):  27.888
total OASDI beneficiaries (M) 44.567
total    UI beneficiaries (M)  6.475
$ 
```

So, the new CPS file has more OASDI beneficiaries and more aggregate OASDI benefits.  I'm OK with those changes.

My question is about the UI benefits.  My memory of the earlier discussion in #146 was that the old CPS data undercounted UI benefits by a lot.  Maybe I'm not remembering correctly or was always confused, but the scaling up of UI benefits in the new CPS data is much smaller than I expected.  The new UI benefits are only three percent larger than the old UI benefits (27.888 versus 27.086).

I'll wait on my Tax-Calculator work until I get a response from you on this.

**Comment by andersonfrailey** [comment]
Thanks for pointing this out, @martinholmer. I'll look into it and get back to you.

**Comment by andersonfrailey** [comment]
@martinholmer, I believe the issue is with the growth factors. When I look at the raw CPS file, I get a weighted sum of unemployment benefits is about ` $43.5 billion`. However, when the data is read into tax-calculator, blow up factors are applied and in 2014 `AUCOMP` is `0.641088`. Multiply that by the sum in the raw CPS file and you get `$27.88 billion`.

Maybe we should create a separate growth factors file that is associated with the CPS. This way all of the 2014 factors will be 1.0 and everything else will start from there. Then in the `cps_constructor` method in Tax-Calculator we'll set `gfactors` to this second file.

**Comment by martinholmer** [comment]
@andersonfrailey,  Somehow the new `n1820` variable has gone missing.  When I copy over the #146 `cps.csv.gz` file and look at the variable names in the CSV header, I get this:
```
iMac2:taxcalc mrh$ gunzip -k cps.csv.gz 
iMac2:taxcalc mrh$ ../../csvvars cps.csv | grep n18*
iMac2:taxcalc mrh$ ../../csvvars cps.csv
1 age_head
2 age_spouse
3 e00200p
4 e00900p
5 e02100p
6 e00200s
7 e00900s
8 e02100s
9 e00600
10 e00800
11 e01500
12 e02300
13 s006
14 DSI
15 h_seq
16 ffpos
17 fips
18 blind_head
19 blind_spouse
20 nu18
21 n21
22 ssi_ben
23 vet_ben
24 snap_ben
25 mcare_ben
26 mcaid_ben
27 e02400
28 XTOT
29 filer
30 FLPDYR
31 MARS
32 e01100
33 e01400
34 e03300
35 e03270
36 e20400
37 e32800
38 e19200
39 e18500
40 e03240
41 e17500
42 RECID
43 e18400
44 e00200
45 e00900
46 e02100
47 e00650
48 e00300
49 e00400
50 e01700
51 e19800
52 e20100
53 e03210
54 e03150
55 nu13
56 nu05
57 n24
58 elderly_dependent
59 f2441
60 EIC
61 agi_bin
62 other_ben
```
Where is the `n1820` variable?

**Comment by andersonfrailey** [comment]
>Where is the n1820 variable?

Whoops. I updates the rename section of the file, but not the list of useable variables. Fixing now.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> I believe the issue is with the growth factors. When I look at the raw CPS file, I get a weighted sum of unemployment benefits is about $43.5 billion. However, when the data is read into tax-calculator, blow up factors are applied and in 2014 AUCOMP is 0.641088. Multiply that by the sum in the raw CPS file and you get $27.88 billion.
>
> Maybe we should create a separate growth factors file that is associated with the CPS. This way all of the 2014 factors will be 1.0 and everything else will start from there. Then in the cps_constructor method in Tax-Calculator we'll set gfactors to this second file.

Excellent analysis of the situation!
Is it easier to skip the 2014 blowup logic when using CPS input data?

**Comment by andersonfrailey** [comment]
>Is it easier to skip the 2014 blowup logic when using CPS input data?

This would be a quicker fix. I'll want to come back and look at what changes we would see if we created a separate growth factors file though. That should probably come after we see how the Tax-Calculator results differ with the updated `e02300` and `e02400` values so we can more easily identify what update caused what change in calculation.

**Comment by andersonfrailey** [comment]
Now that all of the changes in this PR have been merged into Tax-Calculator, I'll merge this in the morning.

**Comment by martinholmer** [comment]
@andersonfrailey said about pull request #146:
> Now that all of the changes in this PR have been merged into Tax-Calculator, I'll merge this in the morning.

Great.  Thanks again for this **major** contribution!

**Pull request merged**
