### PR TITLE
Change CPS dummy-variable elderly_dependent to count-variable elderly_dependents

### PR DESCRIPTION
**Pull request by molly-wuAEI**
@andersonfrailey Hey Anderson, I attempted to fix #194 and I hope that the changes I made help to solve the issue!

### CODE REVIEW

**Comment by martinholmer** [comment]
@molly-wuAEI,  Thanks for adding the `elderly_dependents` variable in pull request #251.

The tests failed because, while you did change `elderly_dependent` to `elderly_dependents` in the `tests/records_metadata.json` file, you forgot to increase the value of the "range" "max" field above one.  You would have realized that if you had run the tests on your local computer (by executing `make pytest`) before you commit changes to your local edits-taxdata branch.

Also, I don't see any change from `elderly_dependent` to `elderly_dependents` in the PUF file.  Are those changes coming in a separate pull request?  If so, you should probably edit the title of PR #251 to say that #251 is changing only CPS data.  Also, there's no need to put the date or the issue you're responding to the title.

**Comment by andersonfrailey** [comment]
Thanks for working on this, @molly-wuAEI. To add to what @martinholmer said, the new "max" value for `elderly_dependents` should just be whatever the largest value for `elderly_dependents` is now.

**Comment by martinholmer** [comment]
@molly-wuAEI, the [advice](https://github.com/open-source-economics/taxdata/pull/251#issuecomment-404829387) from @andersonfrailey is excellent.  The tabulations done [here](https://github.com/open-source-economics/taxdata/issues/243#issuecomment-403862570) and [here](https://github.com/open-source-economics/taxdata/issues/243#issuecomment-403873002) as part of the discussion in issue #243 indicate that the "max" "value" should changed from one to three.

**Comment by martinholmer** [comment]
@molly-wuAEI, can you make the needed changes in #251 so that it can be merged today, Friday, July 20th?

**Pull request merged**
